### ISSUE TITLE
Default color scheme not suitable for spectating

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2638] opened 2017-11-20 23:48 UTC
1) "default" makes this colors https://i.imgur.com/tK4AO5P.jpg
2) simplified does not alter colos based on current team selection, making all players appear same color when spectating

**Comment by GoogleFrog** [comment] 2017-11-21 01:14
What is wrong? One team is blue-ish and the other team is red-ish. Are you applying simplified through the top left dropdown? In my experience it made different allyteams have different colours.

**Comment by sprunk** [comment] 2017-11-21 15:24
I interpret 1 as "the allied colours are all dark and the two greens are dull and mould-like". This sounds valid.

I interpret 2 as a duplicate of #1827.

**Comment by Licho1** [comment] 2017-11-22 07:52
Yes two greens look very very similar, more contrasting colors should be in the palette.

**Closed** 2017-12-25 16:27 UTC
Labels: UI
