### ISSUE TITLE
Tanks sometimes not firing.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3039] opened 2018-05-09 09:29 UTC
http://zero-k.info/Forum/Thread/25318

**Comment by GoogleFrog** [comment] 2018-05-21 13:31
Disarm and EMP is involved. The bug seems to actually occur around 8:00 at 4600 4600.

**Comment by sprunk** [comment] 2018-09-05 16:08
1db1ce91f1152c2b4ea354df7749715be264794c
Duplicate of #2982

**Closed by sprunk** 2018-09-05 16:08 UTC
Labels: behaviour, bug
