### ISSUE TITLE
Mex placement with space-modifier not placing the mex

### ISSUE THREAD

**Issue by thomas11111111** [ZeroK-RTS/Zero-K#4261] opened 2020-12-26 04:06 UTC
To reproduce- 
Select any builder, give any order.
Now give  direct-mex (snap on to nearest mex seems unaffected) or area mex + space-mod command, the command is not recieved.
This used to not affect singleplayer until today, and was limited to area mex only until today.
First noticed on 21st

**Comment by sprunk** [comment] 2023-04-17 00:19
Can't reproduce. It's been 2.5 years so most likely it just got fixed in the meantime.

**Closed by sprunk** 2023-04-17 00:19 UTC
