### ISSUE TITLE
Don't fire at radar recursion

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4439] opened 2021-06-28 09:16 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/40807

```
[f=0062260] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowWeaponTarget trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: [GiveOrderToUnit] recursion not permitted
stack traceback:
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: in function 'AllowWeaponTarget'
	[string "LuaRules/gadgets.lua"]:1337: in function <[string "LuaRules/gadgets.lua"]:1313>
	(tail call): ?
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Utilities/ClampPosition.lua"]:57: in function 'GiveClampedOrderToUnit'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1049: in function 'DoUnitUpdate'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1079: in function 'UpdateUnits'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1094: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:960: in function <[string "LuaRules/gadgets.lua"]:958>
	(tail call): ?
	```

**Comment by Arch-Shaman** [comment] 2021-06-28 09:18
duplicate of #4229

**Comment by sprunk** [comment] 2021-06-28 11:42
duplicate of #4229

**Closed by sprunk** 2021-06-28 11:42 UTC
