### ISSUE TITLE
At least some (Ducks, Scallops) submerged units lose LoS completely

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#1876] opened 2017-01-27 21:21 UTC
<subj>. This makes gameplay very weird: floating enemy target is only seen as a radar dot.

**Comment by sprunk** [comment] 2017-01-27 21:25
Duplicate of #1490, plus already fixed in engine https://github.com/spring/spring/commit/9fb8b24bbaf0a1d8904b45d8d22422a12fd07eb7

**Closed by sprunk** 2017-01-27 21:25 UTC
