### ISSUE TITLE
Econ view fails on some maps minimap

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1313] opened 2016-03-01 06:55 UTC
Desert_Plateaus has no mex map on its minimap.

**Comment by GoogleFrog** [comment] 2016-03-01 07:23
On some maps the failure is restricted to pregame. Obsidian_1.3 lacks minimap spots pregame.

**Comment by sprunk** [comment] 2016-03-17 10:51
Duplicate of #395

**Closed by sprunk** 2016-03-17 10:51 UTC
Labels: minor bug
