### ISSUE TITLE
Games can end in a draw 

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3092] opened 2018-05-24 20:00 UTC
I have witnessed games ending in a draw at the very beginning myself.

This is what BigMac claimed on #zk:
[22:55] BigMac: there is this bug when someone exits to lobby during commander choose and rejoins its a draw

More information: http://zero-k.info/Forum/Thread/25489

**Comment by KingRaptor** [comment] 2018-05-26 01:44
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2286

**Closed by KingRaptor** 2018-05-26 01:44 UTC
