### ISSUE TITLE
Commander balanced is broken

### ISSUE THREAD

**Issue by kolboch** [ZeroK-RTS/Zero-K#3327] opened 2018-11-10 19:07 UTC
Can we make some discussion on commander balance ? They are very underpowered, a lot of times i see commander getting wrekt by Mace. How is commander supposed to survive against some bombers, how is it possible that such plane is able to adjust its position during jump of Recon commander even perfectly timed? It is just stupid imo. Commander is useless in this game in its current state. Investing in that unit is pretty pointless as at every point you have to put upgrade into servos to not move 1m/ year. Please discuss.

**Comment by kolboch** [comment] 2018-11-13 20:20
> > Investing in that unit is pretty pointless
> 
> good that you get that unit for free then

This is why it is so vital, if everyone agrees that it is not neccessary just change to some 'more advanced' builder. This is your point ? I think that it is not, so stop picking words from my issue and maybe suggest sth instead of blaming me for trying to make game more balanced.

**Comment by Phytophyte** [comment] 2018-11-13 22:30
> This is why it is so vital, if everyone agrees that it is not neccessary just change to some 'more advanced' builder. This is your point ? I think that it is not, so stop picking words from my issue and maybe suggest sth instead of blaming me for trying to make game more balanced.

Nobody blamed you; rather, nobody committed any more to the issue than you were willing to.

Zero-K has no paid, dedicated balance team; there's nobody here to throw numbers and mechanics around until the balance is perfect.  If you want an issue solved, you'll have to bring more to the process than just complaints.  Specific suggestions on how to fix the issue are a good starting point, and replays that demonstrate the issue are highly desired.

Many players agree with you that there's an issue with commander balance.  I think the problem is that there hasn't been a person to develop and test a solution to implement.

---

For my two cent on the topic, I think renaming Commanders to _Vanguards_ might temper some expectations of the unit.  "Commander" implies an important, central unit; possibly one that the entire army should be based around.  This isn't the case in Zero-K: here, Commanders represent a player's starting resources, buildpower, and military force, but little more.  In fact, they often become rather disposable once the map has been claimed and battle lines have formed.  The name _Vanguard_ might better illustrate the unit's role in the game.

I don't know if anyone wants to bother changing names again, but I wanted to go ahead and put that out there somewhere anyway.

**Comment by GoogleFrog** [comment] 2018-11-14 02:12
This sort of discussion seems better suited to a forum thread. You'll get a wider range of opinions, people can post replays. An issue here is that I agree with your broad sentiment but not with your particular examples.

@Anarchid is being useless again.

**Comment by sprunk** [comment] 2018-11-14 15:39
Some reasons why currently commander modules are not as good as you'd expect:
 * some of the cost you pay is the buildpower. To build a unit you also have to pay some metal for the constructor/factory, with commanders the cost is incorporated into the upgrade cost.
 * currently you have a high degree of freedom with module choice, this means that modules have to be balanced so that their best use (for example: range modules with long-range weapons) does not get too good, meaning their average use (eg. range modules on low range stuff like HMG) will usually be quite bad. @Aquanim's design tries to solve this by giving less but more meaningful choices.
 * commanders have a huge impact on the earlygame already because they are so powerful compared to cheap units. If modules were any good there's the risk the earlygame would revolve entirely around them (which would still be fairly interesting, but we want an RTS not a dota clone).

A redesign of the leveling system to make it competitive would be good, but it takes a lot of design effort and commanders already have a well-defined role (ie. being a kickstart package to start off the game) so as far as I can tell this is not priority work.

**Comment by sprunk** [comment] 2024-01-24 14:39
Commanders have got some survivability since. Otherwise the points in the 5-year-old post above still stand.

**Closed by sprunk** 2024-01-24 14:39 UTC
