### ISSUE TITLE
Handle extra-ranged targets when we move to future engine

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2930] opened 2018-04-21 18:25 UTC
Or LLT etc .. it happens if you build two of them.
OKP prevents EITHER of them from firing.

Is this the new RTS with smart units where you must micro turrets?

http://zero-k.info/Battles/Detail/496450?

**Comment by lhog** [comment] 2018-04-21 19:54
Do you know some reliable way how to reproduce that?

I'm not sure it's OKP related: I toggled OKP off in the replay and the stinger behavior didn't change. Also I tried to replicate it in several standalone games, including the same map and roughly same stinger 3d pos and I couldn't make them act the way they acted in this game. Weird...

**Comment by GoogleFrog** [comment] 2018-04-22 00:28
I found the same inability to reproduce and unrelatedness to OKP.

**Comment by GoogleFrog** [comment] 2018-04-22 01:10
What happened is that the HLT wanted to shoot at an enemy LLT but where blocked for some reason.

**Comment by Licho1** [comment] 2018-04-22 11:26
It seems to happen when they are on spires

**Comment by Licho1** [comment] 2018-04-22 12:14
I had one repro that i think happened like this:

1) stinger was reloading
2) unit A got into range and stinger started tracking it but could not shoot because of reloading
3) unit A got outside range, still visible
4) unit B got into range, but stinger was ignoring it

**Comment by sprunk** [comment] 2018-05-03 06:11
https://github.com/spring/spring/commit/d987965d2f822cbf5830aa9eca2a7bbff6fd43a2

**Comment by lhog** [comment] 2018-05-03 08:03
Is the enough for ZK though? As far as I recall we completely ignore Default Priority is completely ignored and overriden by gadget.

**Comment by sprunk** [comment] 2018-05-04 10:41
Duplicate of #3011

**Closed by sprunk** 2018-05-04 10:41 UTC
Labels: dev engine, task
