### ISSUE TITLE
Allow saving and using commander presets without logging in

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4174] opened 2020-11-06 20:16 UTC
Allow saving and using commander presets without logging in.

This feature would be great for offline play.  You can play skirmish and such right now, but this feature still doesn't work without an online connection and login.

Please add this feature.

Thanks.

**Comment by GoogleFrog** [comment] 2020-11-07 03:03
My recollection is that there is a duplicate of this ticket in the chobby repository.

**Comment by Arch-Shaman** [comment] 2020-11-07 16:29
Duplicate of https://github.com/ZeroK-RTS/Chobby/issues/364

**Closed** 2020-11-07 23:30 UTC
