### ISSUE TITLE
Many broken things in this screenshot of tab playerlist

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2008] opened 2017-03-01 14:55 UTC
![screen00383](https://cloud.githubusercontent.com/assets/1318249/23465097/45d6e224-feeb-11e6-92de-36b76248e5eb.png)

**Comment by sprunk** [comment] 2017-03-01 14:59
"Ramp spam"

**Comment by DeinFreund** [comment] 2017-03-08 16:13
Looks like an outdated version. Reproduce or post replay link please.

**Comment by sprunk** [comment] 2017-04-27 13:59
Closing as outdated (reopen if reproduced).

**Closed by sprunk** 2017-04-27 13:59 UTC
Labels: bug, feedback required, UI

**Comment by DeinFreund** [comment] 2017-04-27 14:01
I should probably give bots better avatars. I do like how clogger looks different on every spring install though.
