### ISSUE TITLE
Chat widgets drop inputs

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#915] opened 2015-07-08 05:45 UTC
The chat widgets, or at least everything but the old Console, have a nasty tendency to unpredictably drop inputs when typing. I'm not sure if this is engine-level or widget-level, but I don't recall it happening with Console, but it happens often with Proconsole.

If it also happens with Console and with no widgets at all, then close this and I'll mantis.

**Comment by GoogleFrog** [comment] 2015-07-08 06:02
https://springrts.com/mantis/view.php?id=4690

**Comment by GoogleFrog** [comment] 2015-07-08 06:02
https://springrts.com/mantis/view.php?id=4690

**Comment by kaen** [comment] 2015-08-30 19:30
https://springrts.com/mantis/view.php?id=4690#c15104

**Comment by dvr333** [comment] 2016-03-25 05:48
This still happens.

**Comment by sprunk** [comment] 2016-04-24 18:55
Duplicate of #1367

**Comment by GoogleFrog** [comment] 2016-04-25 03:22
No, #1367 is a particular proposed solution. There are other ways to resolve the issue.

**Comment by GoogleFrog** [comment] 2017-01-11 05:21
Fixed in engine around September 2016.

**Closed by GoogleFrog** 2017-01-11 05:21 UTC
Labels: minor bug
