### ISSUE TITLE
Default GUI: chat floating mid screen

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1952] opened 2017-02-19 00:39 UTC
This thing http://i.imgur.com/FDhjLeu.jpg
looks very odd/disturbing too.
Chat should never float like that unanchored.

It makes sense to stick it on top below resbar, because it decays up. Topmost line will be visible last so it will always be anchored to resbar element.

**Comment by GoogleFrog** [comment] 2017-02-19 12:05
It doesn't decay up. The only thing you can click on is marker labels so I think it is fine. It is much better for chat to be at the bottom than the top.

**Comment by KingRaptor** [comment] 2017-02-19 12:08
Put chat above minimap? That doesn't disappear when nothing is selected (unlike integral and selections).

**Comment by Licho1** [comment] 2017-02-19 20:48
chat above minimap would work too.

**Comment by sprunk** [comment] 2017-06-21 16:16
Duplicate of #2040, "figure out chat placement".

**Closed by sprunk** 2017-06-21 16:16 UTC
Labels: UI
