### ISSUE TITLE
Make area cloakers contract to exclude decloaked units

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3972] opened 2020-06-13 06:27 UTC
Currently, area cloakers see significant combat use due to their high recloak time. One possibility is to increase the recloak time for units without natural cloak. A more visible and interactive possibility is this ticket.

The change proposed by this ticket is to make it so that area cloakers never cover units that are temporarily unable to cloak (due to being damaged, firing, doing an ability, etc). If a unit changes state from cloaked to uncloaked while under one or more allied area cloakers, then the cloakers reduce their radius such that they are not covering the unit that changed state.

Additional parameters can be used to balance this:
 - The area cloaker should reduce to a radius less than the distance to the unit that triggered the reduction. This could be a constant offset or based on footprint.
 - The area cloaker should reduce the radius quickly, but not instantly, so as to make it clear what caused the reduction and so it looks better.
 - The area cloaker could suffer from a reduced radius growth speed for a short time after the radius is reduced.

One question to answer is how uncloakable units, such as Thug, interact with this.
 - If Thug does not interact with area cloaking at all then it gains a special ability, that of being able to fire without reducing the size of an area cloaker.
 - If Thug effectively repels area cloakers then the rule 'If you can see enemy units in an area then there is no area cloaker' comes about.

Clearly structures should not interact with area cloakers, as then area cloakers would be unusable defensively.

**Comment by sprunk** [comment] 2020-06-13 12:26
Shielded mobiles repelling area cloak creates potential problem with teamplay (the entire army is revealed by a random crossing allied Thug instead of just the Thug) and raises a question about shielded buildings (people will intuit the shield is what causes the problem, but Aegis is a building so shouldn't interact).

**Comment by GoogleFrog** [comment] 2020-06-14 01:51
An ally putting a Thug inside a cloaker is already fairly annoying for all-but the most combat-oriented cloaker uses. With this change it may be a little more likely that the Thug player notices the issue and moves away.

I don't think people will have much trouble distinguishing static structures from mobile units, it is one of the most natural conceptual divides.

**Comment by Lasica** [comment] 2020-06-29 14:18
I'm not sure what's the benefit of this new mechanism. Do you think it's not sufficient to balance area cloaker with higher recloak time and much larger decloak radius for cloaked units?

It's a bit silly that the most powerful form of cloak (in decloak radius) comes in area cloaker that can grant the cloak ability to any unit that may not be balanced around having cloak (contrary to the units having innate cloak). If the units under cloaker had big detection radius (around skuttle's range or higher) it would be easy to combat them with dedicated cloak units and would give less advantage to cloaked riots closing the gap under cloak.

Bigger decloak radius would also alleviate one of the most powerful strategies in the game (at least in teamgames) - cloaked snitches. It would actually force snitch players to use them as intended - laying as traps and waiting for enemies to come using area cloaker as a means to better set closer traps instead of as a means of safe delivery to the center of enemies groups.

Are there any significant drawbacks to higher delcoak radii? Like performance hit for querrying higher volumes?

**Comment by GoogleFrog** [comment] 2020-06-30 00:10
There is technically no issue with larger decloak radii. Balance-wise, I don't think a larger decloak radius would be a relative nerf to combat cloak compared to sneaky cloak. When used in combat, a larger decloak radius will only have effect on units with particularly long reload times (provided enemies have closed range) or that have less range than their decloak radius. To have much effect on combat cloak you would need a decloak radius of at least 300 elmos.

More recloak time sounds like a good cheap change. I have no idea how to do it nicely so someone would have to investigate.

**Comment by Lasica** [comment] 2020-06-30 10:21
Larger decloak radius helps with edge cases like snitches, with riots like Levelers and with counter scouting enemy with cloaked units like Scythes, Widows or Badger mines. I still think it's noticable and worthwhile balance change for these cases.

It also gives more opportunity for suicide scouts like fleas/dirtbags to reveal more and possibly for air units flying by to reveal some.

**Comment by sprunk** [comment] 2024-01-25 13:47
Still desired? There's been the recloak rate nerf 66819a0fd0b925f25572894147841edac5692b4b and the big indirect nerf where Sparrow can spread dust of appearance 76b5266dd5c00f8d9f2f21685956e37bf16e9b78.

**Closed** 2024-01-26 06:58 UTC
Labels: feature, design decision
