### ISSUE TITLE
Watch this replay and check whether terraform broke

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3637] opened 2019-06-27 05:32 UTC
http://zero-k.info/Battles/Detail/738142

**Comment by Cat-Lady** [comment] 2019-06-27 19:30
Terraform wasn't broken in this battle, and no one suggested that it was. Steel_Blue was mentioning different problem in different battle (in a little chaotic digression comment).

The problem, in case of this battle, was that AI sees and tries to nuke leftover, unfinished terra orders by players - even before having "numerical advantage" to see them.

the problem Steel_Blue mentioned was that *after* getting numerical advantage, his Ravens tries to bomb terra orders, when issues area attack order (and were unable too, but kept trying).

**Comment by sprunk** [comment] 2019-07-03 21:07
>the problem Steel_Blue mentioned was that after getting numerical advantage, his Ravens tries to bomb terra orders, when issues area attack order (and were unable too, but kept trying).

bb0bfed26d7a5818cc5c634cbcdf351bd88f284b

>http://zero-k.info/Battles/Detail/738142

Duplicate of #3627

**Closed by sprunk** 2019-07-03 21:07 UTC
Labels: task
