### ISSUE TITLE
Add idle, fight and patrol leashing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3044] opened 2018-05-10 07:12 UTC
See http://zero-k.info/Forum/Thread/25326. Units set to Roam should not have any change to their behaviour.

Fight/Patrol have leashing by default, in the sense that attack commands are destroyed after moving a certain distance, but this system is destroyed if any commands are inserted. Tactical AI often inserts move commands but players could also insert any command.

![image](https://user-images.githubusercontent.com/1318249/39856609-ec86e978-5473-11e8-9d8c-7125c4fe70f6.png)

We will need to detect the origin of units deviating from Fight/Patrol and forcibly remove any attack commands beyond a certain radius. Removing the attack command seems to re-initialize the default leashing system as, given the unit is far enough away, its command is not instantly re-added.

Idle leashing means that a unit returns to its original position after being pushed or giving itself an attack command. The engine seems to implement nothing along these lines. Polling for idle units is fairly easy but may be expensive, and I do not trust the UnitIdle callin. The questions remains as to whether to give units a Move or Fight command to get their back to their old position. The system may look like this:
- Check whether UnitIdle or UnitCmdDone are suitable callins for marking a units 'home' location. We probably need to periodically check to set home as well.
- Delete home when the unit receives and order.
- Periodically check whether a unit with home is idle and not basically at its home.
- Also check whether a unit with a home has given itself an attack command.
- Fight the unit back to its home if it needs to return. In the case of having an attack command it will likely get Attack from the Fight so the Fight leashing will add to its idle leash distance.

Units which have given themselves an attack command will need to check if the enemy is between themselves and their home, as moving back towards their home will be foolish in this case.

**Comment by sprunk** [comment] 2020-11-13 22:06
Looks like a duplicate of #3568.

**Closed by sprunk** 2020-11-13 22:06 UTC
Labels: behaviour, feature
