### ISSUE TITLE
Comshare breaks game balance

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2175] opened 2017-04-16 09:02 UTC
Consider a 8v8 game, one team decides to do a krow rush and does full com share for the time of rush
3 players start in one spot and do the rush(3 * 8 BP + 10 BP from fac) due to the comshare they have huge start metal bonus AND the ability to effectively expand
So comshare allowed them to utilize and balance both rush and expand
This basically forces the other team to do the same or get smashed otherwise...

Another concern is ability to fully control units of lower skilled players thus totally ruining the balance... 1200 elo, 1200 elo, 1200 elo and 2400 elo get merged forming a very dangerous force basically removing the 1200 elo presence from their team

I see comshare can be useful in teaching/guiding but I don't want this to happen at the expense of balance in team games. So disabling this by default and leaving ability to enable as mod option makes perfect sense to me.
Thoughts?

**Comment by DeinFreund** [comment] 2017-04-16 09:58
Commshare can theoretically be fully reproduced just by sharing resources and units. So if commshare is disallowed so should be the ability to share units or metal. The same goes for sharing on resign: if a noob resigns, his units and metal go to the team's strongest player, increasing the team's average Elo. Thus resign would have to mean losing the resigned player's units and metal. Excess metal can't be shared either, otherwise noobs who excess give their team an unfair advantage. Assisting other people's constructions is of yet another easy way of breaking balance. Do you want to lose all these features?

Battles with high skill disparity are bound to be unbalanced and unpredictable. I don't think we should throw overboard all our teamplay mechanisms because of these games. 

A well coordinated team using sharing to their advantage should be rewarded. Countering a Krow rush only requires minor coordination and definitely not commshare.

**Comment by Aquanim** [comment] 2017-04-18 15:49
In general I have enjoyed games which involved comshare (whether on my team, the opponents', or both) less than I enjoyed games which did not involve comshare.

Comments about the balance of comshare could be made as well but I presently choose not to do so.

**Comment by GoogleFrog** [comment] 2017-04-28 07:08
I don't agree with the reasons for keeping commshared stated here by @DeinFreund. A basic conceit of teamgames is that everyone should get to play, even if it is optimal to share everything to the best players.

Currently the poll says that 42% people want commshare possible by default while only 29% want it disabled. I also hear that commshare is often disabled in teams rooms. Perhaps the people who play are not the people who want commshare?

My main worry with disabling commshare is that (in theory) it is a great tool for getting friends into the game and helping them out. Modoptions are rarely used, especially for new players, so commshare is effectively removed if disabled. Perhaps we should make the default depend on the settings? Enable it for coop games and disable for teams?

**Comment by sprunk** [comment] 2017-04-28 13:26
I think this problem with comshare stems from skill difference in games. If a 1100 nub shares his units to a 2500 godde then obviously it creates a bad game. If two ~equal players comshare then it should generally be alright. On that grounds, how about enabling by default in MM (which is supposed to create games of low elo differences) and coop (which inherently has no balance problems) but requiring a modoption in custom (because giant games encompass the entire elo range)?

**Comment by GoogleFrog** [comment] 2017-04-29 14:09
I don't think all commshare problems stem from high skill deviation.

**Comment by DeinFreund** [comment] 2017-04-29 14:47
> A basic conceit of teamgames is that everyone should get to play, even if it is optimal to share everything to the best players.
This is not the fault of comshare. If you want to play optimally you can just give your units to the best player, which is already being done by some newbies. If you're comsharing with the best player instead, you're actually getting more control than by sharing the units completely.

What problem is there that comshare causes but previous sharing options didn't. Is energy/metal/unit share simply hidden well enough that people didn't use it, or is it the shared unit control that makes a difference? In most comshare games, units are assigned to a specific player and pretty much permanently controlled by that player, how's this different from the old system?

From what I've seen in big team games, the cases where people complain about comshare is where it's being used to share metal to the strongest player on the team. Allowing him to quickly construct game deciding units at the beginning or at a fitting time during the match. Awareness for this possibility seems to have been raised since the introduction of comshare, but it could be done equally by sharing metal. Comshare simply makes giving your metal away much easier and less conscious (I doubt everybody joining the share train actually knows what it means, they are simply mimicking their teammates).

What if we instead added a similarly easy to use "continuously share all metal to strongest player until he excesses" button that announces itself in chat like comshare: "nubX is now supporting pro". Wouldn't this be equally overpowered? Or would he also have to share all his units?

**Comment by sprunk** [comment] 2017-04-29 21:00
Assisting allied construction is also a way to share metal, I don't think it'd be good to block it. Personal excess would have to be burnt (or storage removed), too.

Then there's sharing by diverting income. If there was no way to share metal directly then there would rise issues mimicking early BA mex fights. Reclaim and OD payback would become socially reserved for the pro (unless there was full communism).

**Comment by Arch-Shaman** [comment] 2020-08-14 14:27
Unsure if this is still an issue in 2020?

**Comment by sprunk** [comment] 2023-02-17 16:25
There weren't complaints recently so it's probably fine after all (initial hype died off?).
Regardless, this ticket is buried so a complaint should probably make a new one.

**Closed by sprunk** 2023-02-17 16:25 UTC
Labels: design decision, gameplay
