### ISSUE TITLE
Missile range names overlap

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#725] opened 2015-04-25 20:15 UTC
The names of "Tacnuke and EMP" and "EMP AOE" overlap in the missile range display(missilesilo_range.lua). This should probably be fixed either by shifting the side one of them is on, or adding in a rotation element along the circle and setting up the elements along a curve.

**Comment by xponen** [comment] 2015-05-02 01:32
okay tested, it only happen when world is rotated exactly 90 degree,

**Comment by dvr333** [comment] 2015-05-02 01:53
Along which axis? Also, I'm pretty sure "world rotated precisely 90 degrees" implies being in an overview state, or similarly zoomed out, which is common enough that I'm still concerned. Regardless it's probably easy enough to polish, and polish is something we can always use more of.

**Comment by xponen** [comment] 2015-05-02 09:44
its along y-axis. 
I will try the following formula to make the text rotate with camera rotation 
```
if (cs.name == "free") then
  z = -(radius)*cos(cs.ry)
  x = radius*sin(cs.ry)
end
```

**Comment by GoogleFrog** [comment] 2015-05-02 10:09
I can only reproduce this by tilting the camera to look along the ground at an angle completely useless for playing. Provide a screenshot.

**Comment by xponen** [comment] 2015-05-02 11:01
won't happen to overhead cam because the cam can't rotate the world

**Comment by xponen** [comment] 2015-05-02 11:21
![silo range overlap text](https://cloud.githubusercontent.com/assets/2525365/7440882/76597d44-f100-11e4-8871-20047f02a1a1.jpg)

**Comment by Anarchid** [comment] 2015-05-06 20:15
Assuming this is fixed now.

**Closed by Anarchid** 2015-05-06 20:15 UTC
