### ISSUE TITLE
Unable to make units stop moving immediately after leaving factory

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4500] opened 2021-09-03 16:05 UTC
Sometimes I want to make units stop moving immediately after they leave the factory but before they reach the first "get out of the way" waypoint. Mainly do this when I want them to be picked up by charons. 
When telling them to be picked up they ignore the charon and keep moving, wasting time. When I tell them to stop in place where they are they ignore my command and move to a new waypoint next to where I told them to stop, wasting even more time.

**Comment by sprunk** [comment] 2024-01-25 14:30
Duplicate of #4528

**Closed by sprunk** 2024-01-25 14:30 UTC
