### ISSUE TITLE
Consider retexturing flattened areas

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3207] opened 2018-08-11 20:37 UTC
The user "wiecz" had an idea on #zk: "Tremor-ed terrain should have different texture or something, becouse it is hard to see that area is flat if it still has 'hill' texture".

I'm not sure about the details though.

**Comment by sprunk** [comment] 2018-08-11 20:56
Duplicate of #2860

**Closed by sprunk** 2018-08-11 20:56 UTC
