### ISSUE TITLE
Fix the sun and fog

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1427] opened 2016-06-07 08:44 UTC
Dev engine claims to give us the power to override map sun and fog. There are some otherwise good maps with really bad settings. Investigate whether this ability is real and then fix some maps.

**Comment by GoogleFrog** [comment] 2016-06-08 11:35
Added a widget with per-map overrides. https://github.com/ZeroK-RTS/Zero-K/commit/1d1fb47592962cffdcfd537143ce9c2fed3ea6df

**Comment by Orfelius** [comment] 2016-07-06 20:47
Do you require a list of maps that need to be fixed?

**Comment by GoogleFrog** [comment] 2016-07-07 03:13
Yes, that is the task at the moment. Even better would be someone to write the configs for the maps and make a PR. There is already an example config in place.

**Comment by sprunk** [comment] 2018-11-14 15:40
Duplicate of #3333 (well actually the other way around but this one is buried deep and the new one already has some examples)

**Closed by sprunk** 2018-11-14 15:40 UTC
Labels: feature, task
