### ISSUE TITLE
Funky dirtbag

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1458] opened 2016-07-14 00:20 UTC
http://zero-k.info/Battles/Detail/423209
Dirbags walk cool, but can't attack structure from the ground.

**Comment by sprunk** [comment] 2016-08-15 23:01
Duplicate of #1461

**Comment by mtroyka** [comment] 2016-08-16 00:30
I don't think that's an accurate assessment. In this case the dirtbags jump onto something, but then land oriented incorrectly and stay that way, unable to attack anything. It's more of a 'crab' behavior than just failing to attack.

**Comment by sprunk** [comment] 2016-08-16 02:20
Fixed the funky orientation. The inability to attack is not related to funkiness and is covered in #1461.

**Closed** 2016-08-16 02:20 UTC
Labels: minor bug
