### ISSUE TITLE
Mex spots aren't showing up on minimap

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1916] opened 2017-02-10 10:41 UTC
This issue used to occur, and then I stopped seeing it, and now it's happening like every other game. Doing "/luaui reload" or toggling resource view does not fix the issue. I suspect it's some engine issue.

EDIT: After alt-tabbing back to the game they magically appeared. I've also seen it randomly fix itself, which is odd.

**Comment by Anarchid** [comment] 2017-02-10 10:46
Sounds more like interplay between zk's use of lua gl (which has historically contained all kinds of fun) and some changes in the way engine draws things in recent versions (though unsure if those are actually used by zk).

If you use compositing or things like hybrid gpus, those are also known for doing weird things.

**Comment by GoogleFrog** [comment] 2017-02-12 06:30
Afaik some maps have always missed mexspots on the minimap. They seem to not take drawing at all. Look at the missile silo range drawer, some appear on the minimap and some do not.

**Comment by Licho1** [comment] 2017-03-10 22:08
Happens on "ultra" details, on "high' it fixes itself even run-time.

**Comment by sprunk** [comment] 2017-03-18 13:17
Duplicate Of #395

**Closed by sprunk** 2017-03-18 13:17 UTC
