### ISSUE TITLE
Economy view without glowing reclaim should be default

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#2975] opened 2018-04-28 04:22 UTC
Watching some new players streaming, it's obvious that metal isn't obvious, so showing the metal spots at all times makes the most sense. However, the reclaim glow is confusing, so that part should be turned off unless turned on. Perhaps f4 would simply toggle MetalFeatures, while the full econ view would be toggled with f5 along with the rest of the interface.

**Comment by Licho1** [comment] 2018-04-28 07:47
Map should be make so that metal is obvious. F4 having glowing metal is imo important.
Having default eco on is ugly (ugly GUI markings) so i would say leave it.

**Comment by dvr333** [comment] 2018-04-28 09:06
Even if it is somehow "obvious", that the map texture could ever be as useful as f4 seems unlikely. Go watch the ReFizzed stream video (I'll link once I'm on a proper computer and not my phone), they saw the marks on Obsidian, said "maybe these are metal?" and only started building mexes in any capacity once I told them about f4 view. 

Ultimately metal spots are one discoloration among many, while the econ view provides more data. I would also think having the show numbers setting as the default would also be both a more useful and more aesthetically pleasing presentation.

**Comment by sprunk** [comment] 2018-04-28 20:32
Duplicate of #1926

**Closed by sprunk** 2018-04-28 20:32 UTC
