### ISSUE TITLE
Constructors get reset in raw move

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3064] opened 2018-05-16 04:03 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/7603

**Comment by sprunk** [comment] 2018-07-22 18:07
2821ae4db7a80e02e07f69c0277d6bbbf04cf35b (duplicate of #3149)

**Closed by sprunk** 2018-07-22 18:07 UTC
