### ISSUE TITLE
Unable to play due to crashes

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3186] opened 2018-07-28 19:11 UTC
When I start the game, the game crashes. Before today, I could restart my computer to fix the crashes, but today, I tried restarting, and I still couldn't play. This is one of the crash logs: https://github.com/ZeroK-RTS/CrashReports/issues/12620

**Comment by sprunk** [comment] 2018-07-28 19:55
Third line from the bottom in that crash log says
`Zero-K.exe Warning: 0 : Spring exit code is: -805306369, user-killed during hang`

**Comment by sprunk** [comment] 2018-07-28 19:56
`[f=-000001] [Chobby] Warning: Game config not found: LuaMenu/configs/gameConfig/LuaMenu\configs\gameConfig\zk/mainConfig.lua`
Possibly corrupt download?

**Comment by F4Tornado** [comment] 2018-07-28 21:21
maybe, I'll try reinstalling

**Comment by F4Tornado** [comment] 2018-07-30 01:12
Reinstalling worked.

**Comment by F4Tornado** [comment] 2018-07-30 14:03
Actually, the day after I reinstalled it, it broke the same way again, and I don't want to reinstall it every time I want to play. https://github.com/ZeroK-RTS/CrashReports/issues/12713

**Comment by Histidine91** [comment] 2018-07-30 14:19
That error is pretty strange but shouldn't cause problems.

The description of the circumstances and the fact that the last line is `Zero-K.exe Information: 0 : Chobbyla >> DiscordOnReady {}` leads me to speculate that this is the same issue with Discord as another guy had previously https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2367

Are you using the Discord desktop app? If so, try using the web app instead or turning off the Discord overlay.

How does it crash exactly? Like, does it have the Windows "program.exe has stopped working" popup window? Does it bring up the "close the program"/"wait for the program to respond" window? Something else?

**Comment by F4Tornado** [comment] 2018-07-30 14:33
Restarting worked, I'm keeping this open so someone can fix the discord problem.

**Comment by ArchShaman** [comment] 2018-07-31 10:14
I think it would be better to close it as it is a chobby related issue (and a duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2367 ). Zero-K issues are typically related to game errors (eg: lua errors, crashes while in game, unit behavior bugs, unit script crashes, etc). Chobby issues revolve around the lobby area (which is pretty much what you're describing here).

**Comment by sprunk** [comment] 2019-03-27 08:04
Duplicate of ZeroK-RTS/Zero-K-Infrastructure#2367

**Closed by sprunk** 2019-03-27 08:04 UTC
