### ISSUE TITLE
Fragment shader "successful compilation" spam

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2072] opened 2017-03-13 04:38 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/337

**Comment by dvr333** [comment] 2017-03-19 13:49
This doesn't show up anywhere in the Lua, at least not verbatim.

**Comment by GoogleFrog** [comment] 2017-04-10 12:21
Duplicate.

**Comment by sprunk** [comment] 2017-04-10 12:58
Duplicate of what? It's not the same as #1930.

**Comment by GoogleFrog** [comment] 2017-04-10 14:42
Oh ok.

**Closed** 2017-04-10 15:40 UTC
