### ISSUE TITLE
Area reclaim and mex aren't visible when started on minimap

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1515] opened 2016-09-14 20:41 UTC
If you start area reclaim or area mex command ON miniminap, it works fine, but command isn't drawn on minimap.

If you start it on ground, command also works and IS visible on minimap.

This is replicable on any map.

**Comment by GoogleFrog** [comment] 2016-09-15 03:37
Same as https://github.com/ZeroK-RTS/Zero-K/issues/1513

This is only useful if you report which maps have this failing.

**Comment by Licho1** [comment] 2016-09-15 07:42
Experimented and fixed bug report

**Comment by sprunk** [comment] 2017-03-18 20:01
Duplicate of #1925

**Closed by sprunk** 2017-03-18 20:01 UTC
Labels: bug
