### ISSUE TITLE
Mexes are stackable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3660] opened 2019-07-20 15:51 UTC
![image](https://user-images.githubusercontent.com/1318249/61580862-ef7e9480-ab59-11e9-8934-c9d05811012f.png)

It appeared to be accidental. Only one mex produced income.

http://zero-k.info/Battles/Detail/748260?

**Comment by sprunk** [comment] 2019-07-22 12:04
Duplicate of #2032

**Closed by sprunk** 2019-07-22 12:04 UTC
