### ISSUE TITLE
Streamline start placement

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1741] opened 2016-12-18 03:38 UTC
New users might end up in skirmish or MP games before doing a tutorial. The start setup UI should be simplified to guide them into the game proper. See: http://zero-k.info/Forum/Thread/23383?postID=168044#168044

**Comment by Licho1** [comment] 2016-12-18 13:36
We could force it client side .. soft force wont prevent trolls but it will
ensure players are minimally trained.. proably a good thing to do.

2016-12-18 4:38 GMT+01:00 GoogleFrog <notifications@github.com>:

**Comment by DeinFreund** [comment] 2016-12-20 05:45
The start positions should probably just be taken from Sprungbox start positions (not to implement the same thing twice). These still have to be added/improved for some featured maps.

**Comment by sprunk** [comment] 2018-02-07 10:52
Duplicate of #2759

**Closed by sprunk** 2018-02-07 10:52 UTC
Labels: enhancement
