### ISSUE TITLE
Look into healthbars performance

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3447] opened 2019-03-09 12:53 UTC
![image](https://user-images.githubusercontent.com/1318249/54071848-7f682400-42c6-11e9-9167-7d3443c62b48.png)

**Comment by Porkch0p** [comment] 2019-04-26 09:51
Looked into this and have a potential optimization in #3535

**Comment by GoogleFrog** [comment] 2019-04-27 03:33
Thanks, but that doesn't seem relevant. The default icon distance is 151 and only non-icon units are processed by healthbars.

**Comment by sprunk** [comment] 2024-01-25 13:34
Duplicate of #3839

**Closed by sprunk** 2024-01-25 13:34 UTC
