### ISSUE TITLE
Strike Com tripped

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2330] opened 2017-06-22 18:04 UTC
![bug](https://i.imgur.com/NakzJQg.png)

**Comment by Anarchid** [comment] 2017-06-22 18:05
Duplicate of #2321; solved in engine.

**Comment by DeinFreund** [comment] 2017-06-22 18:06
Ok, but it's really gamebreaking

**Comment by sprunk** [comment] 2017-06-22 18:06
literally unplayable

**Closed by Anarchid** 2017-06-22 18:05 UTC
