### ISSUE TITLE
Com upgrade menu semi-randomly disappears

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1240] opened 2016-02-01 23:13 UTC
See above.

**Comment by GoogleFrog** [comment] 2016-02-03 14:56
I added echos in https://github.com/ZeroK-RTS/Zero-K/commit/442c8a114b4781d12ac348bdd558296190ca6fbb to try to catch the way that the window is being closed. I can only reproduce the bug in multiplayer games.

**Comment by GoogleFrog** [comment] 2016-02-04 04:52
Added further echos.

**Comment by ArchShaman** [comment] 2016-08-23 17:29
I notice when this bug occurs it says "unit deselected" or something like that. It seems to do it semi-randomly/unknown cause.

**Comment by sprunk** [comment] 2018-05-01 23:48
I couldn't reproduce through chat in multiplayer.

**Comment by sprunk** [comment] 2019-03-23 19:08
According to this post http://zero-k.info/Forum/Post/199174#199174 it gets triggered by auto AFK messages.

**Comment by Licho1** [comment] 2019-03-24 10:11
It happens to me too, it auto closes. Extremely annoying. You click it and it hides, click again, hides .. etc..
Sometimes it stays for 1-2s sometimes for 0.5s

**Comment by GoogleFrog** [comment] 2019-08-15 13:14
<Firepluk> is there any hope to fix a bug with 'com morph menu closing when someone goes afk'?
<Firepluk> reported this years ago, I believe its on github
<Firepluk> this crap is cancerously annoying
<Firepluk> https://github.com/ZeroK-RTS/Zero-K/issues/1240
<Firepluk> still not fixed
<Firepluk> resign?!?!?!!?
<Firepluk> resigned
<Firepluk> every fucking time some nub decided to go afk everyone's who has com morph menu opened will get it auto closed

This is is something to go on. That post says the same thing.

**Closed** 2019-11-12 04:10 UTC
Labels: feedback required, minor bug
