### ISSUE TITLE
Transport AI issues

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2062] opened 2017-03-10 22:13 UTC
- [x] should be default off, cons wander too close to frontlines and transports get killed one by one
 - [x]  when auto transporting con, it got to a hill next to a radar but then it could not get off the hill because con was standing close to radar and could not be picked up.
 - [ ]  when con given manual "embark" command in this state, embark would show "attack" cursor and not execute
 - [ ]  if you selec tunits, queue move, click embark and then move embark gets cancelled. Since units now move and embark is not a real command it should not be cancelled by simple move commands.
 - [ ]  if you keep unit selected while it is being transported, it's move command should be transferred to it's transport (improvement)

http://zero-k.info/Battles/Detail/449460

**Comment by GoogleFrog** [comment] 2017-03-11 02:56
>  if you selec tunits, queue move, click embark and then move embark gets cancelled. Since units now move and embark is not a real command it should not be cancelled by simple move commands.

Embark should be cancelled because overriding a units commands (not holding shift) means "I changed my mind, now do this". It is the clearest UI for canceling embark.

> if you keep unit selected while it is being transported, it's move command should be transferred to it's transport (improvement)

Units cannot be selected while being transported.

**Comment by GoogleFrog** [comment] 2017-03-11 03:14
> when auto transporting con, it got to a hill next to a radar but then it could not get off the hill because con was standing close to radar and could not be picked up.

The con probably could be picked up. Transports were not trying. The only fix I can think of is to reduce transportation dropoff radius.

>  when con given manual "embark" command in this state, embark would show "attack" cursor and not execute

This is a highly confusing part of the UI from the previous version of the widget. If you click embark and the unit has no commands that need moving to it will give you the "transport to" UI. This UI lets you place a command that tell the unit to transport to a location. I'd remove it personally since right clicking then pressing embark does the same thing.

**Comment by GoogleFrog** [comment] 2017-03-11 08:24
I reduced unload radius to fix the unload on hill issue.

**Closed** 2017-12-04 21:38 UTC
Labels: UI

**Comment by sprunk** [comment] 2017-12-04 21:40
Subtask 4 is by design and subtask 5 is invalid, see [GF's comment above](https://github.com/ZeroK-RTS/Zero-K/issues/2062#issuecomment-285836618). Tasks 1-3 are done.
