### ISSUE TITLE
Apply skydust terraform to all units in a multi-build

### ISSUE THREAD

**Issue by thomas11111111** [ZeroK-RTS/Zero-K#3931] opened 2020-05-14 10:51 UTC
select stardust, press B, now hold shift and drag, release.
only the first stardust is raised

**Comment by GoogleFrog** [comment] 2020-05-15 04:05
Wasn't someone working on this? Was it you?

**Comment by thomas11111111** [comment] 2020-05-15 11:07
was not me, just reporting

**Comment by sprunk** [comment] 2023-06-16 14:45
Duplicate of #4142

**Closed by sprunk** 2023-06-16 14:45 UTC
Labels: feature
