### ISSUE TITLE
You should be able to build anything anywhere.

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1107] opened 2015-10-22 21:18 UTC
Atm you can build lets say big bertha on a steep hill by first terraforming column and then placing it on top of it.

There is even convenient GUI that lets you set height by holding mouse over a _flat_ terrain.
This gui should apply to any terrain and any unit, because you can always terraform flat/up/low for it, and it's just annoying extra micro..

Red color would then just indicate "cost".

**Comment by Licho1** [comment] 2015-10-23 08:48
This would also replace engine terrain smoothing function

**Comment by GoogleFrog** [comment] 2015-10-24 13:37
Yes. It is difficult to write though. The current GUI is for building at any height on flat terrain core issues in that it issues two orders. Fulfilling this ticket probably requires a lua implementation of structure placement and drawing in the order queue.

**Comment by Licho1** [comment] 2015-10-25 21:58
It could be "hacked" by allowing all structures to be placed anywhere and intercepting build commands.. though there would be no colored indication..

**Comment by Anarchid** [comment] 2015-10-26 12:09
> There is even convenient GUI that lets you set height by holding mouse over a flat terrain.

I'm pretty sure that either a malicious demon has tricked me with false memory, or you can already build things on blocking terrain by holding LMB down even if the placement grid shows red.

**Comment by Licho1** [comment] 2015-10-26 18:48
Nah you cannot, if you could -> ticket solved :-)

**Comment by mtroyka** [comment] 2015-10-26 19:30
>Nah you cannot, if you could -> ticket solved :-)

It worked for me. o.o

**Comment by Anarchid** [comment] 2015-10-26 20:34
I've just tested it and it worked. Closing ticket as instructed.

**Comment by Licho1** [comment] 2015-10-27 07:25
Right you need to hold it longer apparently than I did. 
So whats left is a minor improvement to allow this to happen without hold-wait

**Comment by mtroyka** [comment] 2015-10-27 11:38
That would be nice. For this particular usage it would be nice if you didn't have to select the height either, unless you click-and-hold to do that specifically.

**Comment by GoogleFrog** [comment] 2015-10-28 12:35
The current UI does not allow me to make solars on cliffs.

**Comment by KingRaptor** [comment] 2017-02-18 11:33
Is this possible with the new pre-terraform system (as used for skydusts)?

**Comment by GoogleFrog** [comment] 2017-02-19 12:01
No, hence the pie in the sky. You can give construction orders to make a terraformed structure and the terraform will be placed. The issue is that queuing a stardust after it will not work on uneven terrain. The stardust has to be queued later or we need some sort of commandFallback which turns into a stardust (which is possible).

**Comment by sprunk** [comment] 2017-06-04 01:07
#1998

**Closed by sprunk** 2017-06-04 01:07 UTC
Labels: design decision, enhancement

**Comment by GoogleFrog** [comment] 2017-06-04 01:45
I thought this would take more nonsense hax than simply fixing command insert. However, my terraform command fallback fix was also something that did not exist at the time.
