### ISSUE TITLE
Chili Proconsole2 doesn't space lines properly with Chili FTL

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#464] opened 2014-12-24 18:11 UTC
When using the Chili FTL framework, the spacing between lines becomes huge in Proconsole2, and the lines of text don't line up with the player name lines. Image linked below.

http://i.imgur.com/MesMe2r.png

**Comment by sprunk** [comment] 2015-05-16 03:34
Duplicate of #332

**Comment by Anarchid** [comment] 2015-05-18 16:56
Closed as duplicate.

**Closed by Anarchid** 2015-05-18 16:56 UTC
