### ISSUE TITLE
Chili error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2252] opened 2017-05-27 13:10 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/1164

[f=0010068] Chili-Error in `Chili Economy Panel Default`:control5 : [string "LuaUI/Widgets/chili/controls/control.lua"]:891: attempt to index field 'parent' (a userdata value)
[f=0010068] stacktrace:
	[string "LuaUI/Widgets/chili/controls/control.lua"]:891
	(tail call): in [?]
	[string "LuaUI/Widgets/chili/controls/control.lua"]:773
	(tail call): in [?]
	...
	[string "-- $Id: camain.lua 3171 2008-11-06 09:06:29..."]:84
	[C]: in pcall
[f=0010068] Removed widget: Chili Economy Panel Default

**Comment by sprunk** [comment] 2017-05-27 13:20
I think it's pretty much a duplicate of #1874 (chili object's parent is of type userdata).

**Closed** 2017-12-29 21:19 UTC
Labels: bug, UI
