### ISSUE TITLE
suggested Playerlist improvement

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#606] opened 2015-03-06 23:14 UTC
[17:02]  Licho btw if there is "rewrite playerlist" it should be done as "hold key to show playerlist"
[17:02]  Licho because player list needs to show more data (like eco) and there will be more still (mute status, push to talk status etc)
[17:03]  Licho i mean "full screen" playerlist

**Comment by xponen** [comment] 2015-03-06 23:15
That remind me of counter-strike's playerlist.

**Comment by dvr333** [comment] 2015-03-08 19:39
Note that some sort of playerlist for spectators with economy (as exists now) is required for any spectating/casting to be useful.

For players, though, this is a great idea.

**Comment by GoogleFrog** [comment] 2017-01-11 06:42
Duplicate of a better formatted ticket. https://github.com/ZeroK-RTS/Zero-K/issues/1620

**Closed by GoogleFrog** 2017-01-11 06:42 UTC
Labels: enhancement
