### ISSUE TITLE
Add matchmaker options to speed up matches

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K#3088] opened 2018-05-23 16:28 UTC
Reference: http://zero-k.info/Forum/NewPost?threadID=25545
by Jazcash 
> 
> I'd like to see some changes to matchmaking to speed it up a bit. Spending 10 minutes in the queue whilst it says there are 15 waiting is no fun. There was a change recently that means if you queue as a party of 2, it will only search for 2v2s. I'd like to see an option to allow for the previous behaviour and the current behaviour so we can get matched on larger teams.
> 
> An option that determines whether you're ok with your party getting put on separate teams would also be cool, preferably defaulting to disabled...

**Comment by sprunk** [comment] 2018-05-23 17:16
Belongs to infra where it is a duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2305 (and by extension of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2295)

**Closed by sprunk** 2018-05-23 17:16 UTC
