### ISSUE TITLE
Dirtbag in mass when jumped causes fatal self-damage

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4369] opened 2021-04-02 09:10 UTC
It seems to be when you jump a number of dirtbags in one spot, they collide with eachother then explode instantly. Is this intentional?

**Comment by sprunk** [comment] 2024-01-23 18:05
Old/buried duplicate of #5168

**Closed** 2024-01-23 18:05 UTC
