### ISSUE TITLE
Settings are not being saved for many steam players

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2996] opened 2018-05-01 08:49 UTC
https://steamcommunity.com/app/334920/discussions/0/1696045708660172376/

I suspect we might have to store configs in the user folder instead of program folder? Remember how zk used to be installed in "My Games"

**Comment by sprunk** [comment] 2018-05-03 20:05
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2253

**Comment by DeinFreund** [comment] 2018-05-03 20:06
I believe that issue is about synchronizing campaign progress, not audio settings failing to be saved locally?

**Comment by sprunk** [comment] 2018-05-03 20:07
Oops the discussion links looked the same

**Comment by sprunk** [comment] 2024-05-28 16:25
ZeroK-RTS/Chobby@736f981c6ab4ef046ef72af6ebd7f535d40060f9

**Closed by sprunk** 2024-05-28 16:25 UTC
Labels: bug, backend
