### ISSUE TITLE
Consider interaction of Puppy with Reclaim Highlight

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#4306] opened 2021-02-22 15:01 UTC
I started up the Puppy campaign mission recently which features a bunch of wrecks lying around on Tartarus, a map with a black texture. I have Reclaim Highlighting set to "With Constructors Selected", and with this setting I can barely see the wrecks while I have my Puppies selected. 

However, I do not really want to choose a setting where I will see wrecks when selecting a generic army, or have to disable the economic overlay to get rid of them.

Not sure whether the best way to resolve this is to just roll Puppies in with Constructors, have an additional option to deal with Puppies, or what.

**Comment by sprunk** [comment] 2021-02-22 15:27
duplicate of #3572

**Comment by GoogleFrog** [comment] 2021-02-23 07:33
How am I going to find #3572 when I look a week later for some low hanging fruit? I don't tend to wade beyond the first few pages because most stuff from two years ago is outdated.

**Comment by sprunk** [comment] 2021-02-23 08:53
The overlay could also use some refinement in other directions. Units with BP and without any ability to reclaim should not highlight the overlay.

**Closed** 2021-02-23 10:35 UTC
