### ISSUE TITLE
Sound issue with 98 only with bass?

### ISSUE THREAD

**Issue by Princereaper** [ZeroK-RTS/Zero-K#597] opened 2015-03-02 12:50 UTC
It hard to explain but it sounds like the bass of the sounds in zero k are really "deep" like the bass has been turned up too high.

It only happens with 98...with 91.0 its fine. Sounds normal.

**Comment by Princereaper** [comment] 2015-03-02 12:53
My headset supports 7.1 surround sound. So i'm guessing it might be something to do with new support for surround sound? buts its not correctly adjusted? maybe?

**Comment by Princereaper** [comment] 2015-03-02 12:58
Here a link to the headset. the 780

http://www.plantronics.com/uk/product/gamecom-780?skuId=sku6430013

**Comment by Princereaper** [comment] 2015-03-02 13:25
I thought it might be surround sound so I clicked stereo option but it still has this "bass/deep" aftereffect like listening to thunder in the distance.

**Comment by GoogleFrog** [comment] 2015-03-03 00:34
Test examplemod https://github.com/ZeroK-RTS/ExampleMod

You may have to add a sound which causes you problems.

**Comment by GoogleFrog** [comment] 2015-03-03 00:37
Report and follow here: https://springrts.com/mantis/my_view_page.php

**Comment by GoogleFrog** [comment] 2015-03-03 01:04
Update your audio drivers.

**Comment by lhog** [comment] 2015-03-03 10:06
All sounds in my 98.0+ games  sound like if they have echo.

**Comment by GoogleFrog** [comment] 2015-03-04 01:31
Update your audio drivers.

**Comment by Princereaper** [comment] 2015-03-04 08:21
yeah that the best way to describe it all the sounds have a echo to them and my audio driver is updated.

**Comment by lhog** [comment] 2015-03-04 10:00
Drivers are up-to date. I don't know why I would update drivers anyway as spring 98 and maybe some previous versions of engine are only ones causing echo out of other hundred games?

**Comment by GoogleFrog** [comment] 2015-03-04 10:20
Because dev spring might be the only one of those games that uses openAL and SDL2?

**Comment by Anarchid** [comment] 2015-03-04 10:54
Upgrading OpenAL might be an option for Linux users. Cursory search suggests some other games which use OpenAL have similar (but not same) issues intermittently.

Windows users have a 100% static Spring i think though, so no such option.

**Comment by lhog** [comment] 2015-03-04 18:25
I've done a little bit of science related to the bug.

Here is the replay, where echo could be heard http://zero-k.info/Battles/Detail/333980

I watched this replay on two PCs (both Windows 7)  with two different headsets and echo was hard to NOT notice. However one of the PCs loaded under Linux and tasked to play same replay didn't show any echo. So whatever the bug was, Linux users seem to be immune. Notice engine version was 98.0.1-386

On the never version, i.e. current one, i.e. 98.0.1-398, echo bug does not appear. I assume two sound related commits to spring engine, made between 386 and 398 have done the trick. The sound experience on 98.0.1-398 is the same as on 91.0 for me. If anyone has different experience please report.

**Comment by Princereaper** [comment] 2015-03-04 23:05
windows here

**Comment by Princereaper** [comment] 2015-03-05 10:53
Lastly its echo every battle.

**Comment by Princereaper** [comment] 2015-03-05 12:05
Ok i found out it only 3D sounds as Anarchid points out. The scythes don't make echo. The marker placer beep noise makes echo but the chat beep notifiation doesn't make echo.

**Comment by Princereaper** [comment] 2015-03-05 13:04
Ok the echo happens on speakers but it barely noticable. but it is the same.

**Comment by lhog** [comment] 2015-03-05 13:10
Princereaper, can you check replay I linked and tell us if echo is more audible in that replay than you usually hear in the current development version of engine (98.0.1-398)? Echo is immediately heard once bandits start shooting.

**Comment by Princereaper** [comment] 2015-03-05 14:19
Ok i found out that safe mode fixes it.

**Comment by Princereaper** [comment] 2015-03-05 14:34
Here a video of the issue.
https://www.youtube.com/watch?v=Nm443tAT5b4&feature=youtu.be

**Comment by Anarchid** [comment] 2015-03-05 15:00
The somewhat-fix to this issue is appending 'UseEFX=false` to springsettings.cfg

I'm unsure whether this is a proper fix and what *really* is the root cause.

Closing the issue until further incidents or info.

**Closed by Anarchid** 2015-03-05 15:00 UTC
