### ISSUE TITLE
Recon (only?) coms weapons clip during close fights

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4452] opened 2021-07-10 23:17 UTC
Kissing sessions between recons are often interrupted by weapon clipping. 
https://streamable.com/xplq76 (https://zero-k.info/Battles/Detail/1152491 close to the end)
Have another game  where one com also gets to shoot, can dig up if needed.

**Comment by sprunk** [comment] 2021-07-16 18:50
Duplicate of #4310

**Closed by sprunk** 2021-07-16 18:50 UTC
