### ISSUE TITLE
!poll map is too OP

### ISSUE THREAD

**Issue by completesomething** [ZeroK-RTS/Zero-K#4744] opened 2022-08-15 16:27 UTC
Using `!map` without any arguments in multi-player lobbies essentially guarantees a new map. It makes the assumption that it's already agreed upon that the map should be switched from the current map.

Either `!poll map` should spawn an initial y/n poll asking if the current map should be changed, or the current map should be included in the map roll. For reference, BAR seems to use the first solution, though they don't seem to have the "vote for one of these 4 random maps" aspect of map polling, as they generally manually select maps rather than relying on RNG.

**Comment by sprunk** [comment] 2022-08-15 18:52
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2661

**Closed by sprunk** 2022-08-15 18:52 UTC
