### ISSUE TITLE
Terraform order recursion error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2256] opened 2017-05-28 01:52 UTC
[f=0031125] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=CommandFallback trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3216: GiveOrderToUnit() recursion is not permitted

https://pastebin.com/e7Gi2yry

**Comment by sprunk** [comment] 2017-06-04 02:22
I'll see if engine can be made to allow recursion.

**Comment by GoogleFrog** [comment] 2017-07-18 07:17
Still occurs.

[f=0010042] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=CommandFallback trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3216: GiveOrderToUnit() recursion is not permitted

**Comment by sprunk** [comment] 2017-09-22 10:25
Duplicate of #2522.

**Comment by sprunk** [comment] 2017-09-22 10:32
? Same issue.

**Comment by GoogleFrog** [comment] 2017-09-22 11:40
Disallowing recursion isn't a crash.

**Comment by sprunk** [comment] 2017-09-22 11:43
I see. That other ticket actually has two different terraform errors and I only saw the first one.

**Comment by sprunk** [comment] 2017-09-22 11:45
ZeroK-RTS/CrashReports#2094

**Closed** 2017-09-26 10:35 UTC
Labels: bug, gameplay
