### ISSUE TITLE
Cyclops doesn't approach close enough

### ISSUE THREAD

**Issue by pengvado** [ZeroK-RTS/Zero-K#4034] opened 2020-08-05 13:47 UTC
Cyclops is content to use only one of its weapons. If the enemy is on higher ground, so cannon range is reduced, then Cyclops will move just barely to within slow-beam range and not move a few elmo closer to deploy the cannon; if the enemy is on lower ground, then Cyclops will use only the cannon and not move close enough to deploy the slow-beam. This is clearly tactically sub-optimal.

(Of course, if you manually move to within both weapons' range, then it will use both. But an attack order or attack-move isn't manual enough; only a move order is.)

This behavior also affects all of the other units that have multiple weapons of different ranges, but Cyclops is the only unambiguously problematic case that I noticed; the others you might actually want to behave this way.

**Comment by pengvado** [comment] 2020-08-05 14:03
Oops, duplicate of https://github.com/ZeroK-RTS/Zero-K/issues/3338

**Comment by sprunk** [comment] 2020-08-05 14:08
Duplicate of #3338

**Closed by sprunk** 2020-08-05 14:08 UTC
