### ISSUE TITLE
People who never loaded/showed up become flashing NullAIs

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1846] opened 2017-01-21 07:37 UTC

**Comment by GoogleFrog** [comment] 2017-01-21 13:47
If a unit is created for an AFK team then it should be transferred to a non-afk team. Ideally there would be a mapping function somewhere availible to lagmonitor which gives it a hint about where to send the unit. Otherwise it will go to the highest elo team (with a series of fallbacks).

**Comment by sprunk** [comment] 2017-06-21 15:31
Duplicate of #2114

**Closed by sprunk** 2017-06-21 15:31 UTC
