### ISSUE TITLE
Empire font colour in battle instructions is terrible.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2922] opened 2018-04-20 15:23 UTC
The bold white outline is bad. Other faction text is fine. Other Empire-displaying UI use a different colour.

![image](https://user-images.githubusercontent.com/1318249/39059638-83e2dbf0-4502-11e8-868d-d9b90355fb1d.png)

**Comment by sprunk** [comment] 2018-04-20 15:25
The instruction text is infra-supplied. The small planet panel above is using the hardcoded gameside config.

**Comment by sprunk** [comment] 2018-04-20 15:32
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2207 for the ugliness.
The rest of the ticket is the mismatch between the two colours, which is a duplicate of #2877.

**Closed by sprunk** 2018-04-20 15:32 UTC
Labels: enhancement
