### ISSUE TITLE
Map won't appear on ZK mapserver, no informative error appears in lobby log

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#1012] opened 2015-08-21 19:56 UTC
Map Zed 1.4 can be downloaded and tested here: http://springfiles.com/spring/spring-maps/zed

It is in working order and available on the api here: http://api.springfiles.com/

Despite this, it will not appear on ZK mapserver no matter what I do. When reading the lobby diagnostic log, this is what appears every time:

8/21/2015 1:49:17 PM: No server resource data for maps/zed1.4.sd7, queing upload
8/21/2015 1:49:17 PM: PerformUnitSyncOperation
8/21/2015 1:49:17 PM: UnitSync: Directory: C:\Users\fractalDerivative\Documents\My Games\Spring\engine\100.0
8/21/2015 1:49:17 PM: UnitSync: ZKL: C:\Users\fractalDerivative\Documents\My Games\Spring\
8/21/2015 1:49:18 PM: UnitSync Version: 100
8/21/2015 1:49:18 PM: UnitSync Initialized
8/21/2015 1:49:18 PM: GetUnitSyncData
8/21/2015 1:49:18 PM: UnitSync Disposed
8/21/2015 1:49:18 PM: Could not unitsync file maps/zed1.4.sd7

Due to the non-verbosity of the error, I have no idea why it refuses to unitsync. Could possibly be due to recent server OS upgrade to springfiles by abma? I am unsure and can only speculate. Would love for someone with more knowledge of the internals of the mapserver to investigate.

**Comment by The-Yak** [comment] 2015-08-24 20:15
It's on server now, but the issue remains as outlined by Anarchid on spring forums https://springrts.com/phpbb/viewtopic.php?f=13&p=572694 : 

"I've alleviated the ZK indexing problem somewhat. FWIW: both 1.2 and 1.4 were downloaded and indexed correctly, yet are not findable via zkinfo map search, neither by name nor by author. They are, however, linkable if you have the ID." 

I still think there is issues with mapserver.

**Comment by abma** [comment] 2015-09-01 22:02
wrong bug tracker, this goes to https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues

**Comment by Anarchid** [comment] 2015-09-03 06:23
1) The root cause of the problem was apache upgrade on springfiles breaking all mirroring (including darkstars, jobjol, and zk)

2) Meanwhile, ZKI has a bug where it will only count maps with >1 mirrors as `downloadable`. (https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/777) Non-`downloadable` maps will be indexed and stored in the database, but will not be findable. The bug was triggered by the mirroring problem reducing all new maps' mirror count to exactly 1 (springfiles).

Closing this one.

**Closed by Anarchid** 2015-09-03 06:23 UTC
