### ISSUE TITLE
Feature: Make UI display estimated terraform cost during planning

### ISSUE THREAD

**Issue by Lasica** [ZeroK-RTS/Zero-K#3986] opened 2020-06-29 14:23 UTC
This should help everyone, but especially newbies that are unaware of often huge costs of their terraform projects.

It should support most terraform commands and UI options to issue it. Ideally it should be displayed at the height adjustment phase.

**Comment by sprunk** [comment] 2020-06-29 15:07
duplicate of #1159

**Closed by sprunk** 2020-06-29 15:07 UTC
