### ISSUE TITLE
Consider increased reload time for antinuke

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3140] opened 2018-06-23 06:24 UTC
We should clear up the relationship between nuke and antinuke. I think one antinuke is supposed to be consistently overwhelmed by two silos. One antinuke should be able to defend against a single silo launching multiple nukes in series.

**Comment by sprunk** [comment] 2021-02-22 16:01
Duplicate of #4305

**Closed by sprunk** 2021-02-22 16:01 UTC
