### ISSUE TITLE
Terraformed texture is not preserved after a save and load

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4171] opened 2020-11-04 13:14 UTC
This is important to fix. It happens when you save a game then load it. After loading the grey grid texture of the terraformed areas is replaced by the map texture.

The sad thing is that this was fixed before by GoogleFrog I think, and now that fix was reverted.

Please re-apply the fix and make sure it stays in all future updates.

Thanks

**Comment by GoogleFrog** [comment] 2020-11-04 22:19
When was the fix?

**Comment by deee167** [comment] 2020-11-04 22:56
> 
> 
> When was the fix?

Maybe a year or so ago.  You should be able to check the repository changelog.  We had discussions about it remember?

**Comment by GoogleFrog** [comment] 2020-11-05 12:08
I don't recall this or you had a different name. Your GitHub profile doesn't have such a ticket. If the fix was in lua saves then it isn't relevant (unless engine saves let us save extra data) as we're now using the new engine saves.

**Comment by deee167** [comment] 2020-11-05 12:41
You and I discussed this in game chat.  This was definitely fixed (by you I believe) and it is now broken again.

Just search the git commit messages.

Even if you can't find the commit, could you fix the issue anyway.  This was working and now is broken again.

it's unfortunate that fixes get reverted by other changes.  If you guys don't have automated tests for this and other features maybe you should consider developing them or if that's too hard then maybe keeping a list of things that work and that need testing again when parts of the code are changed might be a good idea.  Just a suggestion to avoid breaking already existing and working features in the future.

Thank you.

**Comment by sprunk** [comment] 2020-11-05 14:19
In this case the underlying save technology changed so it's not just a matter of taking previously working stuff.

**Comment by deee167** [comment] 2020-11-05 16:13
> 
> 
> In this case the underlying save technology changed so it's not just a matter of taking previously working stuff.

But it is a matter of not allowing regression in functionality.  You don't want to break things that worked before.

**Comment by Aquanim** [comment] 2020-11-08 00:51
Since the current save/load functionality works entirely differently to the old one on a technical level, from the technical side of things this is not the same thing that was broken and fixed previously. It is a direct regression from the _user's_ point of view but not from the _developer's_ - which (combined with the fact that this problem involves the engine) means that a quick fix is likely to be more difficult to achieve.

**Comment by sprunk** [comment] 2021-09-03 10:34
Buried duplicate of #4498.

**Closed by sprunk** 2021-09-03 10:34 UTC
Labels: minor bug, graphics
