### ISSUE TITLE
Acquire higher resolution explosion decals

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1628] opened 2016-11-20 21:20 UTC
The resolution of the marks left on the ground by the Roach, the Strategic Nuclear Missile (fired by the Silencer) and probably other explosions as well seems to be too low. Please consider acquiring larger textures for the aforementioned marks. An option to switch to smaller textures could also be offered in case the new textures have a significant performance impact.

**Comment by sprunk** [comment] 2016-12-09 16:36
As far as I know the same set of decals is used for all explosions, chosen at random. So the entire decal set would have to be HD and it would mean random tiny explosions (eg Thug) would also have to use them.

**Comment by mtroyka** [comment] 2016-12-09 16:43
The current decal textures are only like 256x256, which is really only big enough for the smallest size usages. I think larger sized textures would not make much difference, and you could probably do significantly better just by upping them to 512x512.

**Comment by sprunk** [comment] 2017-07-17 11:31
Duplicate of #2409

**Closed by sprunk** 2017-07-17 11:31 UTC
Labels: task
