### ISSUE TITLE
LUA OOM Crashes

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#3390] opened 2019-01-01 20:23 UTC
> [f=0023614] Error: [LuaUI::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=PlayerChanged trace=[Internal Lua error: Call failure] not enough memory
> [f=0023614] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805306657,805306368}bytes
> [f=0023614] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805306657,805306368}bytes
> [f=0023615] game_message: West has been destroyed!
> [f=0023615] game_message: East wins!
> [f=0023615] > Team 2 resigned
> [f=0023732] [Firepluk] didnt survive to drp Anarchid
> [f=0023848] Fatal: [Game::ClientReadNet][LOGMSG] sender="Firepluk" string="[spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805306657,805306368}bytes"
> [f=0023848] Fatal: [Game::ClientReadNet][LOGMSG] sender="Firepluk" string="[spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805306657,805306368}bytes"

Linux, large team game
Happens at game start and at game end, regularly. Have to `/luaui reload` everytime...
I'm not sure what's going on here... is 805306368 805mb max memory LUA can use? Why it's so low my system has 16gb of ram...

```
[duser@localhost zero-k]$ free
              total        used        free      shared  buff/cache   available
Mem:       16301980     7560280     2955928      199848     5785772     8197260
Swap:       8220668           0     8220668
```

**Comment by GoogleFrog** [comment] 2019-01-09 05:13
The engine is leery of giving lua more space. Link a replay and I may be able to run the memory leak device on it. Since you mentioned luaUI you should send your lua config as non-default widgets may leak with few reports.

**Comment by Arch-Shaman** [comment] 2020-08-15 17:03
Isn't this resolved with the modern engine update a while back (the one we switched to 64bit?)

**Comment by sprunk** [comment] 2020-08-26 12:12
It just pushes OOM back in time without solving the underlying problem of why the memory usage is so high.

**Comment by let4be** [comment] 2020-11-25 14:45
Haven't seen this issue for a while... if we use 64bit on windows we can probably close this

**Comment by sprunk** [comment] 2020-12-04 19:03
Duplicate of #2660.

**Closed by sprunk** 2020-12-04 19:03 UTC
Labels: bug
