### ISSUE TITLE
Wrong unit selection when clicking on idle constructors while more constructors are being built

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K#1348] opened 2016-03-23 09:47 UTC
If you click on "idle" constructors while another constructor is being built, sometimes the one that's being built would be selected, instead of the actual idle constructor.

**Comment by sprunk** [comment] 2016-03-23 12:44
Duplicate of #834

**Closed by sprunk** 2016-03-23 12:44 UTC
