### ISSUE TITLE
Fragment shader CUS error - broken #if

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1930] opened 2017-02-13 12:05 UTC
See https://github.com/ZeroK-RTS/CrashReports/issues/98

**Comment by GoogleFrog** [comment] 2017-04-10 12:22
Not fixed. Some units became invisible. https://github.com/ZeroK-RTS/Zero-K/commit/c5b13d74df90fcbd582761907c65b5cee65baf68

**Comment by sprunk** [comment] 2017-07-27 15:58
```
Custom Unit Shaders:, Fragment shader failed to compile with the following errors:
ERROR: 0:75: error(#71) Syntax error incorrect preprocessor directive
WARNING: 0:75: warning(#64) Unexpected tokens following the preprocessor directive - expected a newline(#if )
ERROR: 0:79: error(#71) Syntax error incorrect preprocessor directive
WARNING: 0:79: warning(#64) Unexpected tokens following the preprocessor directive - expected a newline(#if )
ERROR: 0:80: error(#198) Redefinition specular
ERROR: 0:81: error(#198) Redefinition reflection
ERROR: 0:108: error(#71) Syntax error incorrect preprocessor directive
WARNING: 0:108: warning(#64) Unexpected tokens following the preprocessor directive - expected a newline(#if )
ERROR: error(#273) 5 compilation errors.  No code generated
```

I believe this is a duplicate of #2440.

**Closed by sprunk** 2017-07-27 15:58 UTC
Labels: graphics, minor bug
