### ISSUE TITLE
Lua Error in B1111780

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4395] opened 2021-05-09 11:57 UTC
[f=0021012] [Game::ClientReadNet][LOGMSG] sender="LightningCount" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: [GiveOrderToUnit] recursion not permitted
stack traceback:
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: in function 'AllowWeaponTarget'
	[string "LuaRules/gadgets.lua"]:1337: in function <[string "LuaRules/gadgets.lua"]:1313>
	(tail call): ?
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Utilities/ClampPosition.lua"]:57: in function 'GiveClampedOrderToUnit'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1049: in function 'DoUnitUpdate'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1079: in function 'UpdateUnits'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1094: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:960: in function <[string "LuaRules/gadgets.lua"]:958>
	(tail call): ?"

Full infolog:
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/6447443/infolog.txt)

**Comment by sprunk** [comment] 2021-05-09 12:24
Duplicate of #4229

**Closed by sprunk** 2021-05-09 12:24 UTC
