### ISSUE TITLE
Command Center too close to enemy team

### ISSUE THREAD

**Issue by Vistritium** [ZeroK-RTS/Zero-K#2080] opened 2017-03-13 22:45 UTC
The defenders command center was closer to attackers making it easy prey without real possibility to be defended. 

http://zero-k.info/Battles/Detail/449856

**Comment by sprunk** [comment] 2017-03-17 12:58
Duplicate of #2070 which is a subset of #2065

**Closed by sprunk** 2017-03-17 12:58 UTC
