### ISSUE TITLE
Terraform cannot see Adv. Geo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1857] opened 2017-01-22 13:16 UTC
Check out the geo on the right side of this map: http://zero-k.info/Battles/Detail/444157

Terraform did not care about the existence of the Adv Geo. The terraform square was raised with no pyramid construction around the inside of the square which held the structure. The structure would reset it's Y coordinate periodically correctly. My guess is that the position of the Adv Geo was not snapped to the grid that all structures exist on due to a failure in morph.

**Comment by sprunk** [comment] 2017-01-22 21:22
Duplicate of #1417?

**Comment by GoogleFrog** [comment] 2017-01-22 21:53
Perhaps the comment on that ticket is also the cause of this one.

**Comment by GoogleFrog** [comment] 2017-01-22 22:02
Newly created structures don't suffer from this issue though.

**Comment by sprunk** [comment] 2017-02-07 18:09
Fixed by b574f7bc90e08e420086d9e1c6ad78e16feb1a06 ?

**Comment by GoogleFrog** [comment] 2017-02-08 00:18
That commit just fixes a pyramid error for structures already seen.

**Comment by sprunk** [comment] 2019-10-17 13:30
The replay has become tears in the rain.

**Closed by sprunk** 2019-10-17 13:30 UTC
Labels: gameplay, minor bug
