### ISSUE TITLE
Zoom wheel is reversed

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#853] opened 2015-06-16 23:17 UTC
Zoom wheel direction got suddenly reversed to old spring's illogical state, applies to non-COFC cameras.

**Comment by GoogleFrog** [comment] 2015-06-17 02:42
This bug appears after cache is automatically deleted by the recent ZKL commit. Gameside we have no control over scrollwheelspeed so somehow the ZKL self updated caused by the cache deleted also changed or deleted springsettings.cfg.

The value within it should be ScrollWheelSpeed = -25 and all settings in resources have this value set.

**Comment by Anarchid** [comment] 2015-09-18 13:21
Closing as infra issue; open on ZKI tracker if still valid.

**Closed by Anarchid** 2015-09-18 13:21 UTC
