### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2779] opened 2018-02-13 02:19 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/3464

[f=0070857] game_message: Stardust is under attack
[f=0070923] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCreated trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/weapon_impulse.lua"]:332: GiveOrderToUnit() recursion is not permitted
stack traceback:
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Gadgets/weapon_impulse.lua"]:332: in function 'PushPullToggleCommand'
	[string "LuaRules/Gadgets/weapon_impulse.lua"]:392: in function 'UnitCreated'
	[string "LuaRules/gadgets.lua"]:1415: in function <[string "LuaRules/gadgets.lua"]:1410>
	(tail call): ?
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Utilities/clampposition.lua"]:46: in function 'GiveClampedOrderToUnit'
	[string "LuaRules/Gadgets/ai_cai.lua"]:748: in function 'makeWantedDefence'
	[string "LuaRules/Gadgets/ai_cai.lua"]:1361: in function 'conJobHandler'
	[string "LuaRules/Gadgets/ai_cai.lua"]:2911: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1014: in function <[string "LuaRules/gadgets.lua"]:1012>
	(tail call): ?
[f=0071092] game_message: Sling is under attack
[f=0071416] game_message: Radar Tower is under attack
[f=0071764] game_message: Picket is under attack
[f=0072000] useRapidReaim, false
[f=0072023] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitFinished trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/endgame_graphs.lua"]:116: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:116: in function 'UnitFinished'
	[string "LuaRules/gadgets.lua"]:1432: in function <[string "LuaRules/gadgets.lua"]:1425>
	(tail call): ?
[f=0072172] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitFinished trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/endgame_graphs.lua"]:116: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:116: in function 'UnitFinished'
	[string "LuaRules/gadgets.lua"]:1432: in function <[string "LuaRules/gadgets.lua"]:1425>
	(tail call): ?
[f=0072258] game_message: Sling is under attack
[f=0072333] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitFinished trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/endgame_graphs.lua"]:116: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:116: in function 'UnitFinished'
	[string "LuaRules/gadgets.lua"]:1432: in function <[string "LuaRules/gadgets.lua"]:1425>
	(tail call): ?
[f=0072479] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitFinished trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/endgame_graphs.lua"]:116: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:116: in function 'UnitFinished'
	[string "LuaRules/gadgets.lua"]:1432: in function <[string "LuaRules/gadgets.lua"]:1425>
	(tail call): ?
[f=0072893] game_message: Stardust is under attack
[f=0073800] useRapidReaim, true

**Comment by GoogleFrog** [comment] 2018-02-13 02:25
The only possibility I see here is that CAI used GiveOrderToUnit to create a Newton, which then received a GiveOrderToUnit regarding its push/pull state. Why this would cause recursion, I do not know.

**Comment by sprunk** [comment] 2018-02-13 09:53
Duplicate of #2702. This can cause recursion because giving a build order in range can create the nanoframe immediately (within order execution).

**Closed by sprunk** 2018-02-13 09:53 UTC
