### ISSUE TITLE
Chili Economy Panel Default crashes on game start

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2692] opened 2017-12-23 00:09 UTC
Since recently I'm getting error every time I play with a human player. Here is excerpt:

```
[f=-000001] Mex Placement Initialised with 20 spots.
[f=-000001] UpdateInterfacePreset, default
[f=-000001] Chili-Error in `Chili Economy Panel Default`:warningImage : [string "LuaUI/Widgets/chili/controls/control.lua"]:262: attempt to index local 'p' (a userdata value)
[f=-000001] stacktrace:
	[string "LuaUI/Widgets/chili/controls/control.lua"]:262: in GetRelativeBox
	[string "LuaUI/Widgets/chili/controls/control.lua"]:343: in AlignControl
	[string "LuaUI/Widgets/chili/controls/control.lua"]:376: in Realign
	[string "LuaUI/Widgets/chili/controls/control.lua"]:773
	...
	[string "-- $Id: camain.lua 3171 2008-11-06 09:06:29..."]:84
	[string "LuaUI/Widgets/api_chili.lua"]:109
[f=-000001] Removed widget: Chili Economy Panel Default
[f=-000001] GameID: 91823d5a5ad056803265a20052e9c7a9
[f=-000001] Connection attempt from wesley_bos
[f=-000001]  -> Version: 104.0.1-92-g4409317 maintenance
[f=-000001] Epicmenu: Switching to Total Annihilation camera mode
[f=-000001]  -> Connection established (given id 0)
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="wesley_bos" string="[PreGame::GameDataReceived][map-checksums={0x1,0x28527cc6}]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="wesley_bos" string="[PreGame::GameDataReceived][mod-checksums={0x1,0xebf43c07}]"
[f=-000001] Connection attempt from ivand
[f=-000001]  -> Version: 104.0.1-92-g4409317 maintenance
[f=-000001]  -> Connection established (given id 1)
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="ivand" string="[PreGame::GameDataReceived][map-checksums={0x1,0x28527cc6}]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="ivand" string="[PreGame::GameDataReceived][mod-checksums={0x1,0xebf43c07}]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="wesley_bos" string="[PE::CalcChecksum][BLK_SIZE=16][SHA_DATA=11b7fb8b44926bcc1847ddc61d0d6b055d3904af4b72e04eabb168d8f94ef7a9fc5f50099e0788dd9ad94daa676efcfe1bfbbce30ffc463c7552464e66a52e1d]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="wesley_bos" string="[PE::CalcChecksum][BLK_SIZE=32][SHA_DATA=7a9e6412468651d7e1dec06f3fd636b26df675e08455e9c97c852b0cc20b6c62412382600ed3019aa86a8970f500e326d1ab80ee688a8c5beb220635807dd014]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="ivand" string="[PE::CalcChecksum][BLK_SIZE=16][SHA_DATA=11b7fb8b44926bcc1847ddc61d0d6b055d3904af4b72e04eabb168d8f94ef7a9fc5f50099e0788dd9ad94daa676efcfe1bfbbce30ffc463c7552464e66a52e1d]"
[f=-000001] [Game::ClientReadNet][LOGMSG] sender="ivand" string="[PE::CalcChecksum][BLK_SIZE=32][SHA_DATA=7a9e6412468651d7e1dec06f3fd636b26df675e08455e9c97c852b0cc20b6c62412382600ed3019aa86a8970f500e326d1ab80ee688a8c5beb220635807dd014]"
```

Symptoms: I don't see my eco values (income, expense, stored amount, etc,). The eco bar widget frame stays in place, but the bars are empty.

To restore the widget functionality I have to do /luaui reload, which is tedious.

**Comment by KingRaptor** [comment] 2017-12-24 01:50
Duplicate of #1874

**Comment by sprunk** [comment] 2017-12-24 09:25
@lhog Could you share your widget config (and any extra local Chili-using widgets you might have)?

**Comment by lhog** [comment] 2017-12-24 11:45
Here it's. I don't think I use any non-standard chili widgets.

[Config.zip](https://github.com/ZeroK-RTS/Zero-K/files/1584784/Config.zip)

**Comment by lhog** [comment] 2017-12-25 16:21
I can't replicate the same bug when I host a game with my dummy - ivand2. Regardless of whether I or the dummy host the game.

That said I encounter the bug every time I play with wesley_bos. Perhaps there is anything special about wesley, so he crashes my economy bar?

**Closed** 2017-12-29 17:48 UTC
Labels: bug, UI
