### ISSUE TITLE
Endgame graph buttons no longer highlight

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2261] opened 2017-05-30 06:35 UTC

**Comment by CrazyEddieTK** [comment] 2017-05-30 21:16
Cannot reproduce using current master branch.

![image](https://cloud.githubusercontent.com/assets/7810334/26605321/87aab2e6-455b-11e7-8c11-9cdb3238ce9b.png)

![image](https://cloud.githubusercontent.com/assets/7810334/26605342/990c7f2e-455b-11e7-9cd8-bdf54cf28e99.png)

![image](https://cloud.githubusercontent.com/assets/7810334/26605351/a21601b2-455b-11e7-86ce-1e2931070230.png)

**Comment by CrazyEddieTK** [comment] 2017-05-30 21:18
... unless you mean that they don't _remain_ highlighted _after_ you click on them? That's been the case for at least quite some time (maybe always?). My midgame-toggle PR fixes that.

**Comment by GoogleFrog** [comment] 2017-05-31 00:39
The selected graph button was orange before your changes.

**Comment by CrazyEddieTK** [comment] 2017-05-31 01:32
![image](https://cloud.githubusercontent.com/assets/7810334/26611931/7fad70dc-457f-11e7-8ad2-1db20f2ea6be.png)

**Comment by GoogleFrog** [comment] 2017-05-31 03:02
Yea I think I was misremembering. I thought they they highlighted because I tried your PR and was quite confused about which graph was selected.

**Comment by CrazyEddieTK** [comment] 2017-05-31 05:25
My midgame-toggle PR adds orange highlighting to the selected button. This should make it _less_ confusing as to which graph is selected.

It also pre-selects the first button the first time the Stats screen is displayed, rather than showing an empty screen prior to selecting a button (as is the current case). It remembers which button is selected when switching between Awards and Stats and when toggling the screen off and on.

When the game ends, it resets the selected button back to the first button (but displays the Awards screen, not the Stats).

**Comment by CrazyEddieTK** [comment] 2017-06-01 13:54
Can probably close this issue now.

**Closed** 2017-06-01 14:03 UTC
Labels: minor bug, UI
