### ISSUE TITLE
Eco overlay no longer shows mexes on map

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1513] opened 2016-09-11 21:27 UTC
http://i.imgur.com/x5zxmAZ.jpg

**Comment by mtroyka** [comment] 2016-09-11 21:32
I've also seen that happen across various versions and engines. Whenever it happened it seemed random to me, but it was definitely annoying.

**Comment by GoogleFrog** [comment] 2016-09-12 04:44
This has always happened. The failure seems to be somewhat random and map dependent. There are probably different ways of specifying minimaps and some of them refuse to be drawn on by lua.

**Comment by sprunk** [comment] 2017-03-17 17:29
Duplicate of #395

**Closed by sprunk** 2017-03-17 17:29 UTC
Labels: bug
