### ISSUE TITLE
Constructors cancelling current queue and returning to one spot

### ISSUE THREAD

**Issue by Matgenius04** [ZeroK-RTS/Zero-K#5188] opened 2024-02-12 05:47 UTC
## Type of problem: 
**Bug**

## Description of problem:
When I merge with another player, I find that certain constructors stop listening to me and only work within a specified area. If I command them to move anywhere outside of their currently stationed area, they will cancel all items in the queue and just make a beeline back to wherever they were before. 

This issue seemingly doesn't apply to anything other than constructors and even then, it only affects certain groups of constructors. I don't believe it affects me if I don't merge with another player. The other thing I haven't tried is merging with a player other than my friend. I'm not certain if this affects other people.

## [Example game of behavior](https://zero-k.info/Battles/Detail/1828013)
In the linked replay, I've found one such instance happening around 35:25 min into the game (66-67% progress) where if you look at the bottom left corner near the 4 mex, you'll see that I sent some constructors to move into the bottom middle mexes, but they magically redirect themselves back.

Also this is my first time writing an issue like this, so please let me know if there's a certain format that I need to follow for this.

**Comment by sprunk** [comment] 2024-02-12 09:15
> When I merge with another player, I find that certain constructors stop listening to me

At a glance this sounds like they are listening to the other guy whom you're merged with. Make sure your friend isn't using something that would control the constructors automatically (for example the Global Build Commands widget).

**Comment by Xendergo** [comment] 2024-02-14 01:33
Hi, I'm the friend even though the username's different...

I don't have global build commands enabled and the only widgets I have enabled that seem relevant to constructors are auto patrol nanos, auto repair, and smart nanos.

This issue doesn't happen to me in our games, all of the constructors listen to my commands just fine.

Are there any config/log files/anything else that would be helpful for me (or my friend) to upload?

**Comment by sprunk** [comment] 2024-02-15 06:21
> the only widgets I have enabled that seem relevant to constructors are auto patrol nanos, auto repair, and smart nanos.

Perhaps try disabling these for a while and see if it helps. Commands not given locally are somewhat harder to detect so maybe these widgets think your friend is just another widget giving those commands. In that case this ticket would be a duplicate of #3884 essentially.

**Comment by Xendergo** [comment] 2024-02-19 05:36
Disabling widgets seems to fix the problem. Thank you!

**Comment by sprunk** [comment] 2024-02-19 08:59
Cool, thanks.

**Closed as completed by sprunk** 2024-02-19 08:59 UTC
