### ISSUE TITLE
Jumping to the same location sometimes causes units to explode

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3788] opened 2020-02-12 22:54 UTC
At 7:52 at the bottom left of this replay I jump two healthy Recon Commanders together to catch a Jugglenaught: https://zero-k.info/Battles/Detail/834396

The commanders lose health nigh instantly and explode, likely costing the match.

**Comment by sprunk** [comment] 2024-01-23 18:05
Old/buried duplicate of #5168

**Closed** 2024-01-23 18:05 UTC
