### ISSUE TITLE
A constructor that is being built has its priority reset when it is finished building

### ISSUE THREAD

**Issue by beamer159** [ZeroK-RTS/Zero-K#1645] opened 2016-11-28 06:03 UTC
When a constructor is being built, its priority can be set to low, medium, or high. However, when the constructor is finished building, its priority is reset to medium. In the the top picture, the conjurer's priority is set to high while it is being constructed. In the bottom picture, its priority was reset to medium when it was fully constructed.

![screen00000](https://cloud.githubusercontent.com/assets/7436252/20657698/e74659bc-b505-11e6-8f35-ae8f99274f86.png)
![screen00001](https://cloud.githubusercontent.com/assets/7436252/20657702/ed5d8d2a-b505-11e6-8ace-3e75997dad14.png)

**Comment by GoogleFrog** [comment] 2016-11-28 07:01
This is because there are effectively two distinct priority commands: constructor priority and constructiee priority. Every nanoframe has constructiee priority and non-normal constructiee priority overrides constructor priority for the build task. In-progress constructors, factories etc.. get constructor priority upon completion.

Should it not work this way? In other words, should constructor priority be inherited from constructiee priority upon completion? It sounds fairly easy to change.

**Comment by beamer159** [comment] 2016-11-28 07:14
I would say yes, the constructor priority should inherit the priority from the constructiee. Since the game gives the player the option to change priority of the constructiee, that implies that the priority will carry over to the constructor when it is finished constructing.

**Comment by sprunk** [comment] 2016-11-28 17:46
That implication is unfortunate, since these are different things. You might want to have two opposing settings on the same constructor.

For example:
 * I'm making an exponential nanofarm in the corner with some misc infra like jammers or antis. Each nano has high buildee priority because I maximize nanos but low builder priority so that the jammers get built only if there's not enough BP for nanos.
 * later on I have enough eco to make an army. Now nanos get low buildee priority so they are only created if there's not enough BP for the army, but finished ones get high so that the army gets done first.

**Comment by beamer159** [comment] 2016-11-28 17:58
I see, I didn't understand that all units/structures have a priority when being constructed. I thought that only constructors did, and that their priority was for their building priority, not their "being built" priority.

Hmm, still, I think it would be nice if constructors could have their building priority set even as they are being built. At the very least, the way things currently are can be confusing. I'm not sure the best way to go about it though.

**Comment by Licho1** [comment] 2016-11-29 10:04
I woudlnt complicate it i works as designed.
Being able to "order" unfinished units is really the odd thing here that breaks the stuff a bit. Not worth fixing.

**Comment by sprunk** [comment] 2016-11-29 10:11
You can give orders and change all other states on unfinished units! Priority not being able to do this is the odd one out.

**Comment by Anarchid** [comment] 2016-11-29 15:44
Afaict on/off also cannot be given to nanoframes meaningfully.

**Comment by sprunk** [comment] 2016-11-29 17:58
Yes, on/off should be fixed.

**Comment by sprunk** [comment] 2016-11-30 16:46
Reopened for the priority or the on/off?

**Comment by GoogleFrog** [comment] 2016-12-01 02:35
For the priority discussion, as per the title and tag. At the moment I think it would be good to have the priority inherited for consistency with other state toggles. Note that this behaviour might be due to start unit state, it contains separate entries for constructor construction priority and construction constructiee priority. The widget may require modification to allow inheritance from constructiee state, the gadget itself would not even need changing.

**Comment by Licho1** [comment] 2016-12-01 14:34
No, inheritance is extremely bad idea.
Often I do high priority on construction, like on nano or con but i never ever want it to inherit that.

**Comment by Licho1** [comment] 2016-12-01 14:35
If this is about inheriting priority, just no, It is this way by design, I was well aware of that when doing priorities.

**Closed by Licho1** 2016-12-01 14:35 UTC
Labels: design decision
