### ISSUE TITLE
Team option + rejoin can result in uncontrollable units

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#3051] opened 2018-05-11 18:15 UTC
From user Slinterg (same username in ZK and Discord):
> We have some problems now. In mm we team with friend then i disconnected, after reconnect we team up again and we cant control all new builded army and structures
cos it was "dead" player
but build by our controlled builders and fac

**Comment by DeinFreund** [comment] 2018-05-11 20:25
Duplicate of #3050

**Closed by DeinFreund** 2018-05-11 20:25 UTC
Labels: minor bug
