### ISSUE TITLE
cloaked units are cloaked for everone under eraser

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#2305] opened 2017-06-11 19:23 UTC
I asked all in mumble they can confirm. You cannot see the units under eraser.

![screen00025](https://user-images.githubusercontent.com/5669626/27013859-1ec873b8-4eec-11e7-896b-624a9ff4702e.png)

**Comment by GoogleFrog** [comment] 2017-06-12 04:59
Cannot reproduce on ScorpioBattleground. I did not notice this problem while playing cloaky in various MM 1v1s over the past few days. Can reproduce on Zed 2.2 and I also noticed that Zed 2.2 spams shader errors.

Looks like @The-Yak flew too close to the sun.

**Comment by The-Yak** [comment] 2017-06-12 07:53
Fixed in next version

**Closed** 2017-06-12 08:12 UTC
Labels: bug, graphics, map
