### ISSUE TITLE
Report pannel strangeness with unstandard letters

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#4333] opened 2021-03-08 21:35 UTC
https://i.imgur.com/8UFPxR2.png

for me and Inde_Idre the underscore character seems to be very bad in this ingame report menu

**Comment by sprunk** [comment] 2021-03-08 21:58
Duplicate of Chobby#781

**Closed** 2021-03-09 05:03 UTC
