### ISSUE TITLE
Helberd cannot be built above underwater cliffs by Athena

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4738] opened 2022-08-06 16:52 UTC
Despite being a hovercraft.

**Comment by sprunk** [comment] 2022-08-07 23:28
I can't reproduce with just water.

I can reproduce when there is a slope on the seafloor that the Halberd wouldn't be able to path on if there was no water. Engine issue.

**Comment by sprunk** [comment] 2022-08-08 01:52
https://github.com/beyond-all-reason/spring/pull/334

**Comment by sprunk** [comment] 2022-08-15 01:53
Fixed in engine.

**Closed by sprunk** 2022-08-15 01:53 UTC
Labels: engine
