### ISSUE TITLE
Bertha on does not check line of fire before firing

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3370] opened 2018-12-02 12:43 UTC
A bertha set to fire at will chooses to bombard targets that are behind a mountain, instead of aiming at other targets that it would have a free line of fire against.

http://zero-k.info/Battles/Detail/651530

![bertha](https://i.imgur.com/3rfT3vb.png)

**Comment by sprunk** [comment] 2018-12-03 10:22
Duplicate of #2675

**Closed by sprunk** 2018-12-03 10:22 UTC
Labels: engine
