### ISSUE TITLE
Snitch moves while burrowed

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3548] opened 2019-05-04 10:33 UTC
http://zero-k.info/Battles/Detail/712867

**Comment by sprunk** [comment] 2019-05-06 12:35
Most likely a duplicate of #3548

**Comment by sprunk** [comment] 2024-01-24 16:26
There has since been a fix that may have been related: 9487fb17c18f2a5aa1eb276aeffb30ae29a88a6e
Hard to confirm because ancient replay.

**Closed by sprunk** 2024-01-24 16:26 UTC
