### ISSUE TITLE
Campaign: Starting terraform not saved

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#3028] opened 2018-05-06 11:17 UTC
Start Lovaza Jira; save; load; the ramps to the SW/NE corner islands are gone even though the terraform texture is still there.

A manually created mound and a crater from detonating 12 Skuttles were both saved/loaded correctly.

**Comment by sprunk** [comment] 2022-01-17 16:12
Buried duplicate of #4595 (with the fix probably no longer applying since the move to engine save?)

**Closed by sprunk** 2022-01-17 16:12 UTC
Labels: minor bug
