### ISSUE TITLE
Anonymous ffa

### ISSUE THREAD

**Issue by izirayd** [ZeroK-RTS/Zero-K#4146] opened 2020-10-14 05:12 UTC
When playing ffa, a high rank is a common argument to start opposing a certain player, which forces lower level players to oppose a higher ranked player.

Player 1 of the highest rank.
Player 2 of average rank.
Low rank player 3.

Player 2 convinces Player 3 to attack Player 1, based on the fact that Player 1 is a strong player, then Player 3 attacks Player 1 along with Player 2, Player 2 kills Player 1, and after Player 3, Player 2 wins.

Player 3 and Player 1 will benefit from the victory of Player 1, as they will both lose less Elo.

Rank information is meta information for ffa match.

The next reason is also important. Quickly rush an ogre or a mace to capture the enemy's spot.

Strong players, seeing that a low-ranked player is nearby, instantly take him spots. Anonymous ffa will require a thorough analysis of the enemy's army/eco, while still having a complete lack of understanding of the opponent's play style and combat skills (micro macro).

**Comment by izirayd** [comment] 2020-10-14 05:18
I must clarify that this should be an option mode

**Comment by sprunk** [comment] 2020-10-14 17:59
Duplicate of #3895

**Closed by sprunk** 2020-10-14 17:59 UTC
Labels: feature
