### ISSUE TITLE
another issue is the layout where resized map does not push other elements out

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4242] opened 2020-12-18 12:20 UTC
not the player list or the selection panel
was working ages ago
so its a clear regression
another is that after latest update, i have no noises despite widget running

**Comment by sprunk** [comment] 2021-03-02 00:17
>resized map does not push other elements out
Duplicate of #2691

>i have no noises despite widget running
Duplicate of #2077

**Closed by sprunk** 2021-03-02 00:17 UTC
