### ISSUE TITLE
Language menu doesn't confirm language selection

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2889] opened 2018-04-10 08:43 UTC
The language change is not confirmed to the user. Selecting a different language should at least lead to a confirmation window saying "Language switched to X" or something similar.

**Comment by sprunk** [comment] 2018-04-10 10:47
Should just be radiobox imo

**Comment by sprunk** [comment] 2018-04-10 12:32
Also duplicate of #494

**Closed by sprunk** 2018-04-10 12:32 UTC
