### ISSUE TITLE
Tab playerlist is confusing to non-colorblind people

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K#2096] opened 2017-03-18 13:44 UTC
I was watching http://zero-k.info/Battles/Detail/450440 and pressed tab. This is what it showed:
![red-green](https://cloud.githubusercontent.com/assets/2241548/24071105/605f26fa-0c16-11e7-81a5-089d0bf4b8cc.png)
This is confusing to people who can distinguish red and green, because the color of the team name doesn't  match the color for the player. That is because the names have switched places.

**Comment by Anarchid** [comment] 2017-03-18 13:52
I think the top labels are supposed to contain team names, like Northwest vs Southeast.

**Comment by sprunk** [comment] 2017-03-18 13:55
In a 1v1 the teams are named after players.

**Comment by DeinFreund** [comment] 2017-03-18 14:40
Duplicate of #2089

It happens because spectators can change allyteam midgame.

**Comment by Licho1** [comment] 2017-03-18 19:39
Still the labels are confusing.. Team "norm0616" which has player "hedgehogs"?

**Comment by sprunk** [comment] 2017-03-18 19:40
Why reopen? Swapped labels are covered by #2089 already.

**Comment by Licho1** [comment] 2017-03-18 20:51
Sorry, didn't know

**Closed by Licho1** 2017-03-18 20:51 UTC
