### ISSUE TITLE
troubles with group key remap

### ISSUE THREAD

**Issue by Gyslain** [ZeroK-RTS/Zero-K#2257] opened 2017-05-28 13:03 UTC
Guys, I want to remap the units group selection keys (6 7 8 ...) to the f1 f2 f3 ... keys. Here is my lua file :  [zk_keys.lua](https://pastebin.com/eCTfCW10)
With remapped keys, several things don't work :
* if I press f5 (it should correspond to the group 0), I lose the mouse pointer and I can't get it back. I have to quit the game to have it back.
* the definition of groups with alt+f1 does not work, I have to do alt+6 (whereas 6 is binded to "None") to make it works. Then I can press f1 to select my group of units

Could you please tell me what is wrong?

Note : I run on Ubuntu. I tested on windows, but these mapped keys seems to not work at all :(

**Comment by GoogleFrog** [comment] 2017-05-29 04:29
What do you mean by the definition of groups? Where is that bound? Autogroup is a widget and probably has hardcoded hotkeys at the moment.

F5 is bound to hide UI by default. For all I know there could be a widget that intercepts presses of F5 and hides the mouse cursor too. Or perhaps this part of hiding the UI is hardcoded in the engine.

Does Ctrl+F1 work for adding units to a group?

I feel like Ctrl/Alt+F* are key combinations likely to be handled by the OS.

**Comment by sprunk** [comment] 2017-05-29 12:34
>For all I know there could be a widget that intercepts presses of F5 and hides the mouse cursor too.

Yes.

**Comment by Gyslain** [comment] 2017-05-29 17:08
I try to be cleared. I remapped the units group key from 6, 7, 8, 9, 0 to f1, f2, f3, f4, f5 by editing the [zk_keys.lua](https://pastebin.com/eCTfCW10) file because we cannot remap them ingame.
Please check it, at the line 63, I remap the f1 key :
`{"group6", "Any+f1"},` instead of  `{"group6", "Any+6"},`
I do the same way for the others keys.

I don't know how things work and it may not the correct way to redefine the group keys.

**Comment by GoogleFrog** [comment] 2017-05-30 02:15
What is Alt+F1 supposed to do?

**Comment by GoogleFrog** [comment] 2017-05-30 05:00
Fixed F5: https://github.com/ZeroK-RTS/Zero-K/commit/64da23ff477fe52c2ad4e7c70f061857aca03022

Apparently Alt+F1 is only implemented by autogroup and it is hardcoded.

**Comment by GoogleFrog** [comment] 2017-05-30 05:14
This is how I would go about fixing autogroups but there are issues with hotkey order: https://github.com/ZeroK-RTS/Zero-K/commit/d254bd27ff401f8581833f924b929f7706f24343

**Comment by Gyslain** [comment] 2017-05-30 16:55
Great! 
What's the difference between _Any+key_ and _key_ ?
If we simply map _key_ instead of _Any+key_ for group keys, wouldn't this solve the hotkey order issue?

**Comment by GoogleFrog** [comment] 2017-05-31 00:36
You rebinding won't solve the issue in general though.

**Comment by KingRaptor** [comment] 2017-05-31 11:17
> What's the difference between Any+key and key ?

Going off memory: A bind `Any + A` would work if (say) Ctrl + A was pressed, where it would not if the bind was just `A`.

**Comment by sprunk** [comment] 2017-06-01 09:05
Other things that have hardcoded hotkeys which are not modifier keys, enter, or escape:
 * BCV Skydust
 * Q for 0% nanoframe
 * X for blast radius (hold Space+X to see selected unit's death blast radius)
 * 0...9 for `Widgets/gui_group_recall_fix.lua`
 * QWE ASD ZXC for Gesture Menu

**Comment by GoogleFrog** [comment] 2017-06-01 09:17
What is BCV Skydust?

**Comment by sprunk** [comment] 2017-06-01 09:27
Alt+MMB skydust. It also accepts B to toggle the mode and C/V as mousewheel scrolling.

**Comment by sprunk** [comment] 2018-04-20 15:47
Duplicate of #2921 (actually the other way around but that one has less noise)

**Closed by sprunk** 2018-04-20 15:47 UTC
Labels: UI
