### ISSUE TITLE
Commandermodules tooltips are displayed wrong 

### ISSUE THREAD

**Issue by Feugent** [ZeroK-RTS/Zero-K#4151] opened 2020-10-22 11:40 UTC
https://i.imgur.com/V7yzVAj.png

This was changed to an flat speed increase of 3.
Edit: There are actually more tooltips which are displayed wrong e.g. 

    High Power Servos: Speed +8% -> +3
    High Density Plating: Speed -10% -> -3
    Damage Booster: Speed -2.5% -> -1
    Adv. Targeting System: Speed -2.5% -> -1
    Added a speed penalty of -8 to Personal Cloak.

this comes from v1.8.3.2 update  https://zero-k.info/Forum/Thread/29925

**Comment by Sharkgamedev** [comment] 2020-10-22 12:31
This is on the website? If so please move it to Zerok Infrastructure.

**Comment by sprunk** [comment] 2020-10-22 17:04
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2745

**Closed by sprunk** 2020-10-22 17:04 UTC
