### ISSUE TITLE
Sea has degenerated to siren spam (mostly)

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2690] opened 2017-12-21 20:15 UTC
Many sea units don't seem useful in actual games. 
Design or at least balance sweep might be needed.

Also having a tourney with sea map could be useful.

**Comment by Licho1** [comment] 2017-12-21 20:16
Btw combinging "riot + assault" is like an antithesis. You just cannot do it, because you include counter of counter in your unit (assault is countered by raiders which are countered by riot .. )

**Comment by Sgathec** [comment] 2017-12-21 20:23
Isn't it possible to counter the Siren with the Mistral?

**Comment by Phytophyte** [comment] 2017-12-21 22:33
This has been my experience, though from my perspective, the problem is as much the Siren's synergy with the Seawolf, as it is its riot/assault typing.

The Siren's biggest counters are skirmishers and anti-heavy. All of the sea-based skirmishers (Mistral, Scalpel, Buoy) and anti-heavy units (Cutter, Lance, Limpet, maybe Grizzly?) are cannonfodder for the Seawolf. A ship player makes Seawolves to counter these units, and the Sirens demolish everything else. Hence, sea battles are 90% Siren/Seawolf vs Siren/Seawolf.

**Comment by GoogleFrog** [comment] 2017-12-22 01:29
This is not my experience. Siren falls to Lance, Envoy, Corsair, Buoy, Grizzly, Shogun. In low density games some counters are better, in high density games other counters are better. This ticket requires replays.

**Comment by Licho1** [comment] 2017-12-22 09:28
How is your judging of replays different from mine? 
Thats what I saw. People mostly spam sirens because they are good at too many jobs, including killing underwater swarms like ducks. On the other hand, some things are never seen, like limpet. 
If you wish treat it as my note to fix this.

**Comment by Anarchid** [comment] 2017-12-22 11:05
> Note that I'm not saying that it's OP or not counterable. It's just being spammed too much in actual MP games while other units you almost never see. Which is indication of failed design.

It is an indication of players failing to learn the counters. Teams meta is incredibly stale until someone goes in and shocks it. Last times i remember playing sea it quickly turned from Siren spam to Envoy spam simply because Envoy spam beats Siren spam.

**Comment by Aquanim** [comment] 2018-01-04 04:37
Siren has always been problematic in team games. Being slow makes it much more manageable in 1v1. I'll consider changes, although many of them probably require new unit models.

I keep trying to put sea maps into tourneys but almost all of the sea maps are some combination of ugly, poorly designed, too large, too small, or asymmetric.

**Comment by Anarchid** [comment] 2018-01-04 11:31
The map situation being part of why sea is horrible is, i think, a consensus. It is also why i've been campaigning for things like depth-6, and largely why Isle Of Grief and the baobab maps have water. The only way to have good maps when all you have are bad maps is to make good maps (or have them made; inspiring someone with a design rather than doing it yourself can work quite well).

**Comment by Aquanim** [comment] 2018-01-05 06:46
Unfortunately there doesn't seem to be a ton of interest in making water maps from currently active map-makers. I have given some consideration to having a stab at it myself but other tasks are taking higher priority.

A symmetrical map of similar size and metal quantity to conventional small teams maps (think somewhere between Living Lands and Obsidian) would be a good start on appropriate guidelines. That doesn't seem like a high bar but presently (to my knowledge) no such map exists.

**Comment by sprunk** [comment] 2018-01-05 09:06
A low effort way to get sea maps might be to just make `<good land map> Flooded`.

**Comment by Aquanim** [comment] 2018-01-07 00:42
These are some 2v2 replays from the recent tournament:
http://zero-k.info/Battles/Detail/482136
http://zero-k.info/Battles/Detail/482137
http://zero-k.info/Battles/Detail/482138
http://zero-k.info/Battles/Detail/482139
It's probably important to keep in mind that many people are unfamiliar with small teams sea.

**Comment by Aquanim** [comment] 2018-01-13 09:00
Potentially addressed by https://github.com/ZeroK-RTS/Zero-K/commit/0313ad98c3c70db67e58dacf370c293678cd08a4. I'd wait and see what happens before closing.

**Comment by Aquanim** [comment] 2018-01-15 02:18
The bottom half of this battle is a fairly high level 1v1 sea battle:
http://zero-k.info/Battles/Detail/483107
Hard to draw firm conclusions since the land battle played a part in the outcome but the unit compositions don't appear dreadfully unhealthy.

**Comment by Aquanim** [comment] 2018-03-03 23:16
Sea probably still has problems but the siren meta has been slain. Closing.

**Closed by Aquanim** 2018-03-03 23:16 UTC
Labels: gameplay
