### ISSUE TITLE
Minimap is blurry

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#3124] opened 2018-06-13 14:17 UTC
Minimap is rendered blurry. This is a regression.
Worked perfectly previous 10 years.

https://i.imgur.com/4NzPOSs.png

**Comment by The-Yak** [comment] 2018-06-13 17:23
I believe this is triggered by game starting when user has another window in current focus.

**Comment by sprunk** [comment] 2018-08-07 19:49
Duplicate of #3200

**Closed by sprunk** 2018-08-07 19:49 UTC
