### ISSUE TITLE
You should be able to start the game without an internet connection

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4169] opened 2020-11-04 12:31 UTC
Right now if the zero-k updater can't check for updates it doesn't launch the game.

You should be able to play the game offline and over LAN without an internet connection.

Expected behaviour:
-after launching the game, if  the updater can't connect online, it should just start the game anyway
-there should also be a "skip and launch game" button on the updater that the user can press to skip having to wait for the update to fail and launch the game right away

**Comment by sprunk** [comment] 2020-11-04 14:41
Duplicate of #4169

**Closed by sprunk** 2020-11-04 14:41 UTC
