### ISSUE TITLE
Default trees look like something from nightmares

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1993] opened 2017-02-25 22:10 UTC
http://i.imgur.com/UNuUX9F.jpg

**Comment by mtroyka** [comment] 2017-02-25 22:35
Yes they suck. There was a discussion on the spring forums about this, but the solution also sucks because both default trees and any replacements are so small you need a magnifying glass to even see them, and usually if they're used there's 9001 of them on the map.

Really the only way to fix it is to remove them from the offending map and replace them with real trees.

**Comment by sprunk** [comment] 2017-02-25 23:30
Duplicate of #1669

**Closed by sprunk** 2017-02-25 23:30 UTC
