### ISSUE TITLE
2v1 extra commanders

### ISSUE THREAD

**Issue by seedship** [ZeroK-RTS/Zero-K#3862] opened 2020-04-05 03:02 UTC
When hosting custom games with 2v1 or other unbalanced matchups, the downed team does not receive an extra commander, like so: http://zero-k.info/Battles/Detail/865733?

**Comment by GoogleFrog** [comment] 2020-04-05 03:08
An option should be added to modoptions under Start that controls whether uneven teams get extra commanders. The values should be Yes, No and Auto, with Auto doing the current behaviour of giving the commanders only in Teams host types.

**Comment by seedship** [comment] 2020-04-05 03:11
I think Auto should give an extra comm in Custom mode too, as long as no AI are added.



What if as a workaround or alternative solution, there was the option to add a surrender AI which would surrender the moment the game began, thus freeing it's commander?

**Comment by GoogleFrog** [comment] 2020-04-05 05:34
Add a NullAI and doing /take might achieve that.

**Comment by sprunk** [comment] 2023-01-19 16:10
Buried duplicate of #4814

**Closed by sprunk** 2023-01-19 16:10 UTC
