### ISSUE TITLE
Supposedly, AFK auto give to non-afk players stopped working

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1848] opened 2017-01-21 21:37 UTC

**Comment by sprunk** [comment] 2017-01-21 22:04
Replay?

Note that you can disable the giveaway locally (it is a widget).

**Comment by Licho1** [comment] 2017-01-21 22:13
http://zero-k.info/Battles/Detail/444141

**Comment by ArchShaman** [comment] 2017-01-21 22:35
Duplicate of #1841 ?
Related: #1846 ?

**Comment by sprunk** [comment] 2018-02-03 02:15
I looked at chatlogs and mojjj was not actually afk because he immediately responded when people tried to kick him.

**Closed by sprunk** 2018-02-03 02:15 UTC
Labels: minor bug
