### ISSUE TITLE
Reloading saved game on Lalata mission loads with gravity turret launch ramp corrupted

### ISSUE THREAD

**Issue by carn1x** [ZeroK-RTS/Zero-K#3215] opened 2018-08-15 17:04 UTC
The pre-defined ramp for launching units off reloads as a plateau, with a bunch of very steep pits to accommodate the gravity turrets themselves.

**Comment by DeinFreund** [comment] 2018-08-15 17:12
Possibly related to #3028.

**Comment by sprunk** [comment] 2022-01-17 16:25
Buried duplicate of #4595.

**Closed by sprunk** 2022-01-17 16:25 UTC
