### ISSUE TITLE
Refine economy overlay context dependent highlight

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3572] opened 2019-05-19 20:24 UTC
For example when puppies are selected and economy overlay is enabled, wrecks should definitely be highlighted.

![pic](https://i.imgur.com/278LKrX.png)

**Comment by GoogleFrog** [comment] 2019-05-20 02:13
This is a new feature, all I get from this request is that puppies should be considered to be constructors.

The overlay could also use some refinement in other directions. Units with BP and without any ability to reclaim should not highlight the overlay.

**Comment by sprunk** [comment] 2021-02-23 08:49
Duplicate of #4306

**Closed by sprunk** 2021-02-23 08:49 UTC
