### ISSUE TITLE
/take broken when player resigns pre-start

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#580] opened 2015-02-22 22:19 UTC
com idles, flashing in colors, is not given to next highest elo player the whole game

alcur resigned, im the one who should get it.

http://zero-k.info/Battles/Detail/334039

**Comment by mojjj** [comment] 2015-02-22 22:19
also, /take has no effect -.-

**Comment by xponen** [comment] 2015-02-23 03:01
is duplicate of this: https://github.com/ZeroK-RTS/Zero-K/issues/570
I will check the lagmonitor.
@GoogleFrog idea is to not spawn com for non-player

**Comment by xponen** [comment] 2015-02-23 17:38
okay, fixed in https://github.com/ZeroK-RTS/Zero-K/commit/2509b6319fe58da5d84ba4a30da4936a72d1a0dc (stop spawn for resigned player)

**Closed by xponen** 2015-02-23 17:38 UTC
