### ISSUE TITLE
Terraform should provide LOS

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#2842] opened 2018-03-12 02:49 UTC
Currently, when you terraform something and it is out of LOS, you do not actually the results of it. For example, a hole you dug on the other side of a wall you can't see over. The ground would appear flat until you got LOS of the other side, upon which a hole would spontaneously appear.
As can be seen this can [cause confusion](http://zero-k.info/Battles/Detail/490389).

It doesn't  make sense that you can't see the results of your own orders.

**Comment by sprunk** [comment] 2019-04-08 13:26
Duplicate of #2697

**Closed by sprunk** 2019-04-08 13:26 UTC
Labels: gameplay, graphics, minor bug
