### ISSUE TITLE
Bugged Scorcher heatray visuals when shooting vertical wall

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#4527] opened 2021-09-25 04:13 UTC
See screenshots:
![screen00287](https://user-images.githubusercontent.com/2396152/134757376-d5dae5dd-6e0a-418e-9e4e-7b3b76e08738.png)
![screen00294](https://user-images.githubusercontent.com/2396152/134757492-bf0bb9e3-884e-4858-9039-0bbed4261266.png)

Reproduces every time.

**Comment by sprunk** [comment] 2021-09-27 21:45
Duplicate of #4446

**Closed by sprunk** 2021-09-27 21:45 UTC
