### ISSUE TITLE
Serve Linux version on Steam

### ISSUE THREAD

**Issue by rogersachan** [ZeroK-RTS/Zero-K#3711] opened 2019-08-19 04:07 UTC
Currently people have to use the semi-portable archive from itch to play. Making it possible to download from the steam listing would be a more streamlined way to play Zero-K.

**Comment by sprunk** [comment] 2019-08-19 11:04
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2578

**Closed by sprunk** 2019-08-19 11:04 UTC
