### ISSUE TITLE
Lagging really badly

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#3948] opened 2020-05-30 12:59 UTC
i7 2600k, 32gb ram, gtx 1060
springsettings.cfg
https://pastebin.com/WE3n2zKc

late game I get 3-5 fps most of the time, some games I drop to single frame numbers hovering about 1 fps

early game runs super smooth

**Comment by GoogleFrog** [comment] 2020-05-30 13:22
Send an infolog. Making a bug report through Help in the menu sends it all.

**Comment by let4be** [comment] 2020-05-31 15:52
https://pastebin.com/iwzRFEaz

**Comment by let4be** [comment] 2020-05-31 15:53
I tried pressing prtscr during game but it's broken and doesn't take screenshot... I forgot which command in console to take screenshot, why prtscr is not working?...

**Comment by Arch-Shaman** [comment] 2020-08-16 02:35
Is this still happening?

**Comment by sprunk** [comment] 2021-07-27 16:29
I couldn't find anything useful in the infolog. Marking as duplicate of #2148 (same user, also perf issues)

**Closed by sprunk** 2021-07-27 16:29 UTC
