### ISSUE TITLE
Right click on minimap still breaking up

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2079] opened 2017-03-13 22:34 UTC
log: 
https://paste.ee/p/3NYbl

demo:
http://zero-k.info/Battles/Detail/449856

**Comment by GoogleFrog** [comment] 2017-03-14 11:26
Do /luaui disable next time you notice this and then try to give orders with the minimap. Then I would know whether there is a widget interfering.

**Comment by sprunk** [comment] 2017-03-18 20:06
Duplicate of #2060

**Closed by sprunk** 2017-03-18 20:06 UTC
