### ISSUE TITLE
Single player mission 10 does not work

### ISSUE THREAD

**Issue by borisovg** [ZeroK-RTS/Zero-K#2150] opened 2017-04-10 10:44 UTC
When starting mission 10 (Normal Chickens) no commander is created.

**Comment by KingRaptor** [comment] 2017-05-30 07:27
I cannot reproduce this in v1.5.5.1. I suspect any observed non-spawn resulted from previous issues with the commander delayed spawn, that were subsequently fixed by making the comm always drop at the very start of the game. 

Drop a note here if you're still getting the issue

**Closed by KingRaptor** 2017-05-30 07:27 UTC
Labels: bug
