### ISSUE TITLE
The module selection window can close without user interaction

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#2770] opened 2018-02-10 11:20 UTC
The commander module selection window can disappear seemingly for no reason. Then one has to reopen it. I don't know what could cause it.

**Comment by GoogleFrog** [comment] 2018-02-10 11:24
I know it happens and don't know what causes it either. There are debug outputs every time you close the module selection window. Look at what they say when it closes by itself (F8).

**Comment by sprunk** [comment] 2018-02-10 16:50
See #1240

**Comment by Sgathec** [comment] 2018-02-10 17:14
May this be closed then?

**Comment by sprunk** [comment] 2018-03-13 11:48
Duplicate of #1240

**Closed by sprunk** 2018-03-13 11:48 UTC
