### ISSUE TITLE
Show experience somewhere

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3261] opened 2018-09-30 19:44 UTC
That used to reveal facts related to the unit.

**Comment by sprunk** [comment] 2018-09-30 21:52
I'm fairly sure it never did that and the way to do this was to click while holding Space.

**Comment by Sgathec** [comment] 2018-09-30 22:06
No, I don't mean that. You could see the unit experience for example.

**Comment by sprunk** [comment] 2018-09-30 22:16
Right, that one. As far as I can tell that's intended, anything useful is visible on the selection panel (experience is visible as a rank icon).

**Comment by Sgathec** [comment] 2018-09-30 22:17
Fractional experience is not visible as far as I know.

**Comment by GoogleFrog** [comment] 2018-10-04 11:01
Since when can you see experience anywhere? @SgathecI think you are talking about the engine tooltip

**Comment by sprunk** [comment] 2018-10-04 11:32
>Since when can you see experience anywhere?

Rank icons exist. They represent a ballpark value but I believe it would be misleading to have an easily accessible more precise number because experience is not an accurate gauge of anything. Units can "steal" hits from each other, stuff like superweapons don't collect XP because it tends to fire into the fog, there are multiple ways to contribute other than damage (incl. status effect "damage" types), etc. Possibly there could be an icon at some fractional <1.0 xp threshold so people can tell the unit is contributing.

Having it accessible at all sounds good though. I don't think it would be good to put it on the selection panel (see #2642) due to clutter, how about the space+click stats menu?

**Comment by GoogleFrog** [comment] 2018-10-04 12:11
Space+click is not for dynamic stats.

**Comment by sprunk** [comment] 2023-12-03 15:18
Buried duplicate of #5085.

**Closed by sprunk** 2023-12-03 15:18 UTC
