### ISSUE TITLE
Gauss buildable on water

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4008] opened 2020-07-17 20:36 UTC
This has been driving me nuts for some time. Why isn't gauss able to be built on water since it has legs in water now?

**Comment by Licho1** [comment] 2020-07-17 21:07
If everything is buildable in water whats the point of water then? Just an area ships cannot leave?

**Comment by Feugent** [comment] 2020-07-17 22:02
Gauss was never intended to be buildable on water.
Gauss got legs so you can no longer rez them to (OP) underwater gauss, but have them being on water instead.

**Comment by sprunk** [comment] 2020-07-17 23:31
Duplicate of #3244

**Closed by sprunk** 2020-07-17 23:31 UTC
