### ISSUE TITLE
4hundred sometimes breaks chat

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2219] opened 2017-05-11 12:50 UTC
Whenever 4hundred says something with a white name the chat is broken with nonsense characters before their name. This is likely due to the editbox change and some interaction with colour characters.

**Comment by GoogleFrog** [comment] 2017-05-12 04:52
filch can also break chat. It looks like "d(<filch>" and can be seen at the start of this replay http://zero-k.info/Battles/Detail/456716.

**Comment by sprunk** [comment] 2017-05-12 09:19
Duplicate of #2201

**Closed by sprunk** 2017-05-12 09:19 UTC
