### ISSUE TITLE
Jumpjets can jump into sea

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#999] opened 2015-08-18 22:03 UTC
Jump into the water. Live there. Die there.
http://zero-k.info/Battles/Detail/370955

**Comment by GoogleFrog** [comment] 2015-08-19 00:26
The units I have seen are slow and can't fire. So it seems ok to me.

**Comment by sprunk** [comment] 2015-08-19 01:29
My main concern is that it breaks the cliff+water boundary which used to make areas impassable by any ground units. Some maps have recently started featuring that in their design - one example is http://zero-k.info/Maps/Detail/49517 around the starting hill. Now you can just jump into the water first.

Other uses don't seem problematic gameplay-wise but the interface suffers (jump line is red, F2 says not pathable, unit icon says ground only, etc.).

**Comment by GoogleFrog** [comment] 2015-09-08 11:44
Jump isn't reverse landship. Landship is when a unit moves slowly over unpathable terrain. The ticket was misnamed and I responded to the name.

**Comment by GoogleFrog** [comment] 2015-09-08 11:47
The issue is probably that jump tests for steepness. It is unable to test for pathablity (as it once did) because that would block jumping onto structure. The fix for this would be to add a terrain height check.

This is an unusual issue though, what if you wanted to jump a Skuttle onto a shipyard which is near the shore? Should the fix be instead to disable the jump ability for underwater units (barring Recon comm, of course).

**Comment by Anarchid** [comment] 2015-09-09 09:04
I would block jumping *out* of water. Units which are submerged below their maxdepth and are not amphibious lose their ability to move despite not dying, and Jump is a motion ability.

**Comment by GoogleFrog** [comment] 2015-09-09 12:40
My worry is that you may jump a unit into the water (or have it bounce of a jumped-onto structure) and then be unable to get it out. But apart from that I like blocking jumping out of water. On balance I think that is the change I support.

**Closed** 2015-09-12 02:55 UTC
