### ISSUE TITLE
103.0.1-1169 Lua OOM Desync

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2387] opened 2017-07-11 05:57 UTC
Traces:
 * https://github.com/ZeroK-RTS/CrashReports/issues/1486
 * https://github.com/ZeroK-RTS/CrashReports/issues/1487

Battle: http://zero-k.info/Battles/Detail/462395

"[f=0082861] Fatal: [spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805306499,805306368}bytes". Watch the replay to see if there is any nonsense. Consider how to block or fallback from nonsense. Perhaps report on mantis.

**Comment by GoogleFrog** [comment] 2017-07-14 01:04
Terraform may be the problem but it doesn't seem excessive. I had 105MB of lua allocated memory at the time and 1.8GB by Spring in total.
![screen00472](https://user-images.githubusercontent.com/1318249/28193959-38b9b212-6884-11e7-9ae0-cb303a4f23e8.jpg)

**Comment by GoogleFrog** [comment] 2017-07-14 01:07
Maybe they were running other things on their computer.

**Comment by sprunk** [comment] 2019-11-26 11:16
Those are inexperienced randoms so presumably they used Chobby map picker instead of `!map` so I'd guess this is a duplicate of ZeroK-RTS/Chobby#694. The replay is dead and OOM is otherwise a known generic problem with existing tickets (eg. #2660).

**Closed by sprunk** 2019-11-26 11:16 UTC
Labels: bug
