### ISSUE TITLE
Lua NAN in terraform

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#1496] opened 2016-08-26 15:30 UTC
originally reported here: https://springrts.com/mantis/view.php?id=5334
(replay in mantis report)

```
[f=0017411] Error: LuaRules::RunCallIn: error = 2, AllowCommand, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:306: bad argument 0000003 to 'SetUnitRulesParam' (number expected, got NAN (check your code for div0))
[f=0017412] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:306: bad argument 0000003 to 'SetUnitRulesParam' (number expected, got NAN (check your code for div0))
stack traceback:
    [C]: in function 'SetUnitRulesParam'
    [string "LuaRules/Gadgets/unit_terraform.lua"]:306: in function 'SetTooltip'
    [string "LuaRules/Gadgets/unit_terraform.lua"]:3054: in function 'GameFrame'
    [string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
    (tail call): ?
```

**Comment by ashdnazg** [comment] 2016-08-27 08:25
crash/desync is a minor bug? :D

**Comment by GoogleFrog** [comment] 2016-09-02 05:59
I have looked through the code and can't see an obvious way for that number to be NaN. Does Spring immediately crash if NaN is used in arithmetic or does the NaN infect many numbers until it eventually crashes at a callout?

**Comment by ashdnazg** [comment] 2016-09-02 08:31
The latter
There's something setting the height of the ground in at least one spot to NaN which results in propagation to other parts (min/max map height) and eventually it causes an infinite loop in ray tracing

**Comment by GoogleFrog** [comment] 2016-09-02 14:36
Are you saying that, in the engine, the height of a location is being set to NaN?

**Comment by ashdnazg** [comment] 2016-09-02 14:39
I'm saying that lua is calling an engine function that sets height with NaN as an argument

**Comment by GoogleFrog** [comment] 2016-09-02 15:16
Good, that was what I was asking.

**Comment by sprunk** [comment] 2017-07-03 08:37
Duplicate of #2361 (actually the other way around but that one has infologs).

**Closed by sprunk** 2017-07-03 08:37 UTC
Labels: bug
