### ISSUE TITLE
units stuck on reloading, un affected by disarmed

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#3129] opened 2018-06-16 01:56 UTC
in this battle my crab got stuck with 4% reloading and un affected by disarm near the end of the game exit after

https://drive.google.com/file/d/1kme7uLxvHISpstHNJGFDvnAVIxbALyO9/view?usp=sharing

seem to be a long-standing issue . Firepluk reported similar thing with emissary. unknow cause

**Comment by sprunk** [comment] 2018-07-07 01:00
Duplicate of #2982

**Closed by sprunk** 2018-07-07 01:00 UTC
