### ISSUE TITLE
Shogun is very likely to get stuck on Urchins and Tidals.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3290] opened 2018-10-21 06:35 UTC
See http://zero-k.info/Battles/Detail/629964

**Comment by ArchShaman** [comment] 2018-10-21 09:12
Duplicate of #3120

**Comment by sprunk** [comment] 2020-06-16 01:58
The replay is a goner.

**Closed by sprunk** 2020-06-16 01:58 UTC
