### ISSUE TITLE
Hide autohost commands from chat

### ISSUE THREAD

**Issue by nubtron** [ZeroK-RTS/Zero-K#1984] opened 2017-02-25 00:40 UTC
Like the !y responses for votestart.
It looks like debug log spam, or an unfinished feature.

**Comment by Licho1** [comment] 2017-02-25 09:00
There are two options:
1) cheap clientside hack to hide it
2) replace with server messages

Choose your selection

**Comment by quantumv** [comment] 2017-02-25 12:26
I'd say go for 1)

2) would still spam the chat in large games.

**Comment by sprunk** [comment] 2017-02-25 20:15
I think the point of a server message is that it does not go to chat.

**Comment by Licho1** [comment] 2017-02-25 23:37
yeah server messages would completely skip chat. It would be sent as luaui message ingame and as protocol message in chobby.

**Comment by DeinFreund** [comment] 2017-03-01 00:49
Although this shouldn't be happening, the UI still fails to display votes at times. Having the !y fallback is nice..

**Comment by Sgathec** [comment] 2019-08-03 16:18
I would like to request a new voting design since I find the votes on the chat during battles disruptive as seeing the important parts is hard in big team games. Big team games are difficult to avoid at the most active time of the day unless one is willing to wait a long time to start a medium battle as I believe you can't start a battle larger than 4v4 under an hour usually.

**Comment by sprunk** [comment] 2020-12-07 17:36
Duplicate of #4207 (well actually the other way around but this one is buried somewhere deep where people can't find it)

**Closed by sprunk** 2020-12-07 17:36 UTC
Labels: UX
