### ISSUE TITLE
hivemind glitched after I crashed and rejoined

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#3142] opened 2018-06-23 16:54 UTC
http://zero-k.info/Battles/Detail/567871

All newly created units were put under the non-existing team control...

**Comment by ashdnazg** [comment] 2018-07-04 15:02
I won't be surprised if it's a combination with the afk unit giver.

**Comment by sprunk** [comment] 2018-09-11 00:14
Engine is misbehaving: https://springrts.com/mantis/view.php?id=6039

Alternatively, callins to detect people quitting and rejoining could be made accessible for a Lua solution: https://github.com/spring/spring/pull/369 (would also need `SyncedPlayerAdded` and `Removed`, but so far no feedback even on `Changed`)

@ashdnazg

**Comment by sprunk** [comment] 2019-11-12 03:36
Duplicate of #3142 (actually the other way around but that one has a fresh replay)

**Closed by sprunk** 2019-11-12 03:36 UTC
