### ISSUE TITLE
Ecoview doesn't highlight geospots

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1467] opened 2016-07-21 15:39 UTC
The big yellow line that's supposed to mark geospots is no longer visible for me. Using engine 103.0. Firepluk said he had the same issue and furthermore couldn't see reclaim in ecoview (though I still see glowing wreckages).

**Comment by sprunk** [comment] 2017-10-02 20:11
Duplicate of #2539 and that one has more valuable info.

**Closed by sprunk** 2017-10-02 20:11 UTC
Labels: graphics, minor bug
